CREATE TABLE [DV].[Fact_Case_Daily_Analysis] (
    [CaseID]                                             NVARCHAR (100) NULL,
    [CaseHash]                                           CHAR (66)      NULL,
    [SnapshotDateKey]                                    INT            NOT NULL,
    [ParticipantHash]                                    CHAR (66)      NULL,
    [EmployeeHash]                                       CHAR (66)      NULL,
    [ReferralHash]                                       CHAR (66)      NULL,
    [ProgrammeHash]                                      CHAR (66)      NULL,
    [DeliverySiteHash]                                   CHAR (66)      NULL,
    [RequestorHash]                                      CHAR (66)      NULL,
    [CaseStatusHash]                                     CHAR (66)      NULL,
    [ReferralStatusHash]                                 CHAR (66)      NULL,
    [ReferralDateKey]                                    INT            NULL,
    [PRapReferralCompletedWithinSLA]                     INT            NULL,
    [InitialContactCompletedWithinSLA]                   INT            NULL,
    [InitialAppointmentBookedCompletedWithinSLA]         INT            NULL,
    [InitialAppointmentFailedToAttendCompletedWithinSLA] INT            NULL,
    [InitialAppointmentAttendedCompletedWithinSLA]       INT            NULL,
    [FirstWorkAppraisalCompletedWithinSLA]               INT            NULL,
    [WelcomePackSentCompletedWithinSLA]                  INT            NULL,
    [WelcomePackUploadedCompletedWithinSLA]              INT            NULL,
    [InitialActionPlanUploadedCompletedWithinSLA]        INT            NULL,
    [MonthlyActionPlanReviewCompletedWithinSLA]          INT            NULL,
    [ReferralDocumentsSentCompletedWithinSLA]            INT            NULL,
    [ReferralDocumentsInQueryCompletedWithinSLA]         INT            NULL,
    [ReferralDocumentsResentCompletedWithinSLA]          INT            NULL,
    [ReferralDocumentsCompletedCompletedWithinSLA]       INT            NULL,
    [ProgrammeStartCompletedWithinSLA]                   INT            NULL,
    [FirstContactCompletedWithinSLA]                     INT            NULL,
    [MissedAppointmentsCompletedWithinSLA]               INT            NULL,
    [SubmissionCompletedWithinSLA]                       INT            NULL,
    [InterviewCompletedWithinSLA]                        INT            NULL,
    [OfferAcceptedCompletedWithinSLA]                    INT            NULL,
    [WorkplacePlanAppointmentCompletedWithinSLA]         INT            NULL,
    [JobStartAddedCompletedWithinSLA]                    INT            NULL,
    [JobStartVerifiedCompletedWithinSLA]                 INT            NULL,
    [JobStartDateCompletedWithinSLA]                     INT            NULL,
    [InWorkContactCompletedWithinSLA]                    INT            NULL,
    [ActionPlanUploadedCompletedWithinSLA]               INT            NULL,
    [FirstHMRCPing1FirstEarningsCompletedWithinSLA]      INT            NULL,
    [HMRCPing2_1kCompletedWithinSLA]                     INT            NULL,
    [HMRCPing3_2kCompletedWithinSLA]                     INT            NULL,
    [HMRCPing4ThresholdReachedCompletedWithinSLA]        INT            NULL,
    [FirstHMRCPing5EmploymentEndCompletedWithinSLA]      INT            NULL,
    [JobOutcomePaidCompletedWithinSLA]                   INT            NULL,
    [ProgrammeExitCompletedWithinSLA]                    INT            NULL,
    [ExitReportUploadCompletedWithinSLA]                 INT            NULL,
    [ExitReportDocumentsSentCompletedWithinSLA]          INT            NULL,
    [ExitReportDocumentsInQueryCompletedWithinSLA]       INT            NULL,
    [ExitReportDocumentsResentCompletedWithinSLA]        INT            NULL,
    [ExitReportDocumentsCompletedCompletedWithinSLA]     INT            NULL,
    [ExitInterviewBookedCompletedWithinSLA]              INT            NULL,
    [ExitInterviewFailedToAttendCompletedWithinSLA]      INT            NULL,
    [ExitInterviewAttendedCompletedWithinSLA]            INT            NULL,
    [PRapReferralOutsideSLA]                             INT            NULL,
    [InitialContactOutsideSLA]                           INT            NULL,
    [InitialAppointmentBookedOutsideSLA]                 INT            NULL,
    [InitialAppointmentFailedToAttendOutsideSLA]         INT            NULL,
    [InitialAppointmentAttendedOutsideSLA]               INT            NULL,
    [FirstWorkAppraisalOutsideSLA]                       INT            NULL,
    [WelcomePackSentOutsideSLA]                          INT            NULL,
    [WelcomePackUploadedOutsideSLA]                      INT            NULL,
    [InitialActionPlanUploadedOutsideSLA]                INT            NULL,
    [MonthlyActionPlanReviewOutsideSLA]                  INT            NULL,
    [ReferralDocumentsSentOutsideSLA]                    INT            NULL,
    [ReferralDocumentsInQueryOutsideSLA]                 INT            NULL,
    [ReferralDocumentsResentOutsideSLA]                  INT            NULL,
    [ReferralDocumentsCompletedOutsideSLA]               INT            NULL,
    [ProgrammeStartOutsideSLA]                           INT            NULL,
    [FirstContactOutsideSLA]                             INT            NULL,
    [MissedAppointmentsOutsideSLA]                       INT            NULL,
    [SubmissionOutsideSLA]                               INT            NULL,
    [InterviewOutsideSLA]                                INT            NULL,
    [OfferAcceptedOutsideSLA]                            INT            NULL,
    [WorkplacePlanAppointmentOutsideSLA]                 INT            NULL,
    [JobStartAddedOutsideSLA]                            INT            NULL,
    [JobStartVerifiedOutsideSLA]                         INT            NULL,
    [JobStartDateOutsideSLA]                             INT            NULL,
    [InWorkContactOutsideSLA]                            INT            NULL,
    [ActionPlanUploadedOutsideSLA]                       INT            NULL,
    [FirstHMRCPing1FirstEarningsOutsideSLA]              INT            NULL,
    [HMRCPing2_1kOutsideSLA]                             INT            NULL,
    [HMRCPing3_2kOutsideSLA]                             INT            NULL,
    [HMRCPing4ThresholdReachedOutsideSLA]                INT            NULL,
    [FirstHMRCPing5EmploymentEndOutsideSLA]              INT            NULL,
    [JobOutcomePaidOutsideSLA]                           INT            NULL,
    [ProgrammeExitOutsideSLA]                            INT            NULL,
    [ExitReportUploadOutsideSLA]                         INT            NULL,
    [ExitReportDocumentsSentOutsideSLA]                  INT            NULL,
    [ExitReportDocumentsInQueryOutsideSLA]               INT            NULL,
    [ExitReportDocumentsResentOutsideSLA]                INT            NULL,
    [ExitReportDocumentsCompletedOutsideSLA]             INT            NULL,
    [ExitInterviewBookedOutsideSLA]                      INT            NULL,
    [ExitInterviewFailedToAttendOutsideSLA]              INT            NULL,
    [ExitInterviewAttendedOutsideSLA]                    INT            NULL,
    [PRapReferralOverdue]                                INT            NULL,
    [InitialContactOverdue]                              INT            NULL,
    [InitialAppointmentBookedOverdue]                    INT            NULL,
    [InitialAppointmentFailedToAttendOverdue]            INT            NULL,
    [InitialAppointmentAttendedOverdue]                  INT            NULL,
    [FirstWorkAppraisalOverdue]                          INT            NULL,
    [WelcomePackSentOverdue]                             INT            NULL,
    [WelcomePackUploadedOverdue]                         INT            NULL,
    [InitialActionPlanUploadedOverdue]                   INT            NULL,
    [MonthlyActionPlanReviewOverdue]                     INT            NULL,
    [ReferralDocumentsSentOverdue]                       INT            NULL,
    [ReferralDocumentsInQueryOverdue]                    INT            NULL,
    [ReferralDocumentsResentOverdue]                     INT            NULL,
    [ReferralDocumentsCompletedOverdue]                  INT            NULL,
    [ProgrammeStartOverdue]                              INT            NULL,
    [FirstContactOverdue]                                INT            NULL,
    [MissedAppointmentsOverdue]                          INT            NULL,
    [SubmissionOverdue]                                  INT            NULL,
    [InterviewOverdue]                                   INT            NULL,
    [OfferAcceptedOverdue]                               INT            NULL,
    [WorkplacePlanAppointmentOverdue]                    INT            NULL,
    [JobStartAddedOverdue]                               INT            NULL,
    [JobStartVerifiedOverdue]                            INT            NULL,
    [JobStartDateOverdue]                                INT            NULL,
    [InWorkContactOverdue]                               INT            NULL,
    [ActionPlanUploadedOverdue]                          INT            NULL,
    [FirstHMRCPing1FirstEarningsOverdue]                 INT            NULL,
    [HMRCPing2_1kOverdue]                                INT            NULL,
    [HMRCPing3_2kOverdue]                                INT            NULL,
    [HMRCPing4ThresholdReachedOverdue]                   INT            NULL,
    [FirstHMRCPing5EmploymentEndOverdue]                 INT            NULL,
    [JobOutcomePaidOverdue]                              INT            NULL,
    [ProgrammeExitOverdue]                               INT            NULL,
    [ExitReportUploadOverdue]                            INT            NULL,
    [ExitReportDocumentsSentOverdue]                     INT            NULL,
    [ExitReportDocumentsInQueryOverdue]                  INT            NULL,
    [ExitReportDocumentsResentOverdue]                   INT            NULL,
    [ExitReportDocumentsCompletedOverdue]                INT            NULL,
    [ExitInterviewBookedOverdue]                         INT            NULL,
    [ExitInterviewFailedToAttendOverdue]                 INT            NULL,
    [ExitInterviewAttendedOverdue]                       INT            NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([CaseID]));
GO

