CREATE TABLE [DV].[Fact_CaseActivity] (
    [CaseHash]                       CHAR (66)        NULL,
    [ActivityHash]                   CHAR (66)        NULL,
    [ActivityStartDateKey]           INT              NULL,
    [ActivityCompleteDateKey]        INT              NULL,
    [ActivityDueDateKey]             INT              NULL,
    [IsAttended]                     INT              NULL,
    [IsDidNotAttend]                 INT              NULL,
    [ReferralDateKey]                INT              NULL,
    [StartDateKey]                   INT              NULL,
    [IsLiveReferral]                 INT              NULL,
    [JobOutcomeOneIsPaidDateKey]     INT              NULL,
    [DeliverySiteName]               NVARCHAR (1000)  NULL,
    [FullName]                       NVARCHAR (1000)  NULL,
    [ParticipantID]                  NVARCHAR (1000)  NULL,
    [MobileNumber]                   NVARCHAR (1000)  NULL,
    [ContractStartDate]              DATE             NULL,
    [CaseStatus]                     NVARCHAR (1000)  NULL,
    [ActivityName]                   NVARCHAR (1000)  NULL,
    [ActivityType]                   NVARCHAR (1000)  NULL,
    [ActivityContactMethod]          NVARCHAR (1000)  NULL,
    [ActivityStatus]                 NVARCHAR (1000)  NULL,
    [ActivityStartDate]              DATE             NULL,
    [ActivityCompleteDate]           DATE             NULL,
    [CaseAdvisorName]                NVARCHAR (1000)  NULL,
    [ActivityAdvisorName]            NVARCHAR (1000)  NULL,
    [ReferringJCP]                   NVARCHAR (1000)  NULL,
    [ReferringWorkCoach]             NVARCHAR (1000)  NULL,
    [CaseID]                         VARCHAR (30)     NULL,
    [JobReadinessStatus]             NVARCHAR (1000)  NULL,
    [VacancyGoal1]                   NVARCHAR (1000)  NULL,
    [VacancyGoal2]                   NVARCHAR (1000)  NULL,
    [VacancyGoal3]                   NVARCHAR (1000)  NULL,
    [HasUpToDateCV]                  NVARCHAR (1000)  NULL,
    [BetterOffCalculationStatus]     NVARCHAR (1000)  NULL,
    [IsDriver]                       NVARCHAR (1000)  NULL,
    [PingCount]                      INT              NULL,
    [Ping1Date]                      INT              NULL,
    [Ping2Date]                      INT              NULL,
    [Ping3Date]                      INT              NULL,
    [Ping4Date]                      INT              NULL,
    [Ping1DateActual]                DATE             NULL,
    [Ping2DateActual]                DATE             NULL,
    [Ping3DateActual]                DATE             NULL,
    [Ping4DateActual]                DATE             NULL,
    [Ping0DateCalc]                  INT              NULL,
    [Ping1DateCalc]                  INT              NULL,
    [Ping2DateCalc]                  INT              NULL,
    [Ping3DateCalc]                  INT              NULL,
    [Ping4DateCalc]                  INT              NULL,
    [CumulativeEarningsToDate]       DECIMAL (38, 10) NULL,
    [RemainingEarnings]              DECIMAL (38, 10) NULL,
    [ProjectedDate]                  DATE             NULL,
    [ProgrammeName]                  NVARCHAR (1000)  NULL,
    [Redesign_TotalRowCount]         INT              NOT NULL,
    [ReferralDate]                   DATE             NULL,
    [JobOutcomeOneIsPaidDate]        DATE             NULL,
    [ActivityCompleteDate_MonthYear] NVARCHAR (50)    NULL,
    [JobLeaveaddDateDateKey]         INT              NULL,
    [JobLeaveaddDateDate]            DATE             NULL,
    [IsOverdue]                      INT              NULL,
    [IsInFuture]                     INT              NULL,
    [Isduetodayflag]                 INT              NULL,
    [LastJobEmployerName]            NVARCHAR (1000)  NULL,
    [LastJobJobTitle]                NVARCHAR (1000)  NULL,
    [LastJobWeeklyHours]             DECIMAL (38, 10) NULL,
    [LastJobContractedHours]         DECIMAL (38, 10) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);
GO

