CREATE TABLE [DV].[SAT_DeliverySite_Adapt_Core] (
    [DeliverySiteHash]    BINARY (32)     NULL,
    [DeliverySiteKey]     NVARCHAR (100)  NULL,
    [DeliverySiteName]    NVARCHAR (255)  NULL,
    [Status]              INT             NULL,
    [Zone]                NVARCHAR (255)  NULL,
    [ReportingRegion]     NVARCHAR (255)  NULL,
    [ReportingAreaBranch] NVARCHAR (255)  NULL,
    [ReportingZone]       NVARCHAR (255)  NULL,
    [BaanRegion]          VARCHAR (10)    NULL,
    [BaanAreaBranch]      NVARCHAR (4000) NULL,
    [BaanZone]            VARCHAR (10)    NULL,
    [DSRegion]            NVARCHAR (4000) NULL,
    [TempID]              NVARCHAR (4000) NULL,
    [Ofsted]              VARCHAR (50)    NULL,
    [ROM]                 NVARCHAR (4000) NULL,
    [Delivery]            NVARCHAR (4000) NULL,
    [BranchManager]       NVARCHAR (4000) NULL,
    [BranchManagerEmail]  NVARCHAR (4000) NULL,
    [ROMEmail]            NVARCHAR (4000) NULL,
    [WPSite]              NVARCHAR (4000) NULL,
    [EmailCC]             NVARCHAR (4000) NULL,
    [CPA]                 NVARCHAR (4000) NULL,
    [NorthSouth]          NVARCHAR (4000) NULL,
    [QualityManager]      NVARCHAR (4000) NULL,
    [IsActive]            NVARCHAR (4000) NULL,
    [ReportingHierarchy]  NVARCHAR (4000) NULL,
    [RegionSES]           NVARCHAR (4000) NULL,
    [BranchOwner]         NVARCHAR (4000) NULL,
    [FinanceName]         NVARCHAR (4000) NULL,
    [BranchManagerEmpNo]  NVARCHAR (4000) NULL,
    [WHPLot]              NVARCHAR (4000) NULL,
    [DataOwner]           NVARCHAR (4000) NULL,
    [ContentHash]         BINARY (32)     NULL,
    [ValidFrom]           DATETIME2 (0)   NULL,
    [ValidTo]             DATETIME2 (0)   NULL,
    [IsCurrent]           BIT             NULL
)
WITH (HEAP, DISTRIBUTION = HASH([DeliverySiteHash]));

