CREATE TABLE [DV].[SAT_Assignment_Adapt_Core]
(
	[AssignmentHash] [BINARY](32) NULL,
	[AssignmentKey] [NVARCHAR](100) NULL,
	[AssignmentReference] [VARCHAR](18) NOT NULL,
	[AssignmentTitle] [NVARCHAR](MAX) NULL,
	[AssignmentStartContractType] [DECIMAL](20, 0) NULL,
	[AssignmentLeaveDate] [DATETIME2](0) NULL,
	[AssignmentAddDate] [DATETIME2](0) NULL,
	[AssignmentType] [DECIMAL](20, 0) NULL,
	[AssignmentLeaveReason] [DECIMAL](20, 0) NULL,
	[AssignmentIndustry] [DECIMAL](20, 0) NULL,
	[AssignmentStatus] [DECIMAL](20, 0) NULL,
	[AssignmentStartDate] [DATETIME2](0) NULL,
	[WorkRelatedActivityType] [DECIMAL](20, 0) NULL,
	[ContractedHours] [DECIMAL](5, 2) NULL,
	[AssignmentStartVerificationDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeTwoVerificationDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeTwoFailedDate] [DATETIME2](0) NULL,
	[AssignmentStartClaimDate] [DATETIME2](0) NULL,
	[AssignmentStartClaimYear] [NVARCHAR](MAX) NULL,
	[WorkTrialEndDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeTwoClaimedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeTwoClaimYear] [NVARCHAR](MAX) NULL,
	[AssignmentOutcomeOneFailedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeOneVerifiedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeOneClaimedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeOneClaimYear] [NVARCHAR](MAX) NULL,
	[UnsupportedDate] [DATETIME2](0) NULL,
	[UnsupportedDateVerified] [DATETIME2](0) NULL,
	[SelfEmployed] [NVARCHAR](MAX) NULL,
	[FailedAssignmentStartDate] [DATETIME2](0) NULL,
	[DiscountMilestone] [NVARCHAR](MAX) NULL,
	[AssignmentOutcomeThreeClaimedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeThreeFailedDate] [DATETIME2](0) NULL,
	[AssignmentOutcomeThreeClaimYear] [NVARCHAR](MAX) NULL,
	[AssignmentOutcomeThreeVerifiedDate] [DATETIME2](0) NULL,
	[EmployerConsentGiven] [NVARCHAR](MAX) NULL,
	[AssignmentStartPaymentCycle] [DECIMAL](20, 0) NULL,
	[AssignmentStartFirstPaymentDate] [DATETIME2](0) NULL,
	[AssignmentOwningEmployee] [DECIMAL](16, 0) NULL,
	[AssignmentSelfEmployedVerified] [NVARCHAR](MAX) NULL,
	[WageCategory] [DECIMAL](20, 0) NULL,
	[WeeklyHours] [DECIMAL](6, 2) NULL,
	[HourlyRate] [DECIMAL](11, 2) NULL,
	[WageException] [NVARCHAR](MAX) NULL,
	[TempPerm] [DECIMAL](20, 0) NULL,
	[EstimatedAssignmentEndDate] [DATETIME2](0) NULL,
	[ContentHash] [BINARY](32) NULL,
	[ValidFrom] [DATETIME2](0) NULL,
	[ValidTo] [DATETIME2](0) NULL,
	[IsCurrent] [BIT] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [AssignmentHash] ),
	HEAP
)
GO
