CREATE TABLE [DV].[SAT_DeliverySite_LKRegionZones] (
    [DeliverySiteHash]    BINARY (32)    NULL,
    [DeliverySiteKey]     NVARCHAR (100) NULL,
    [Zone]                NVARCHAR (255) NULL,
    [ReportingRegion]     NVARCHAR (255) NULL,
    [ReportingAreaBranch] NVARCHAR (255) NULL,
    [ReportingZone]       NVARCHAR (255) NULL,
    [BaanRegion]          INT            NULL,
    [BaanAreaBranch]      INT            NULL,
    [BaanZone]            VARCHAR (10)   NULL,
    [DSRegion]            INT            NULL,
    [TempID]              INT            NULL,
    [Ofsted]              VARCHAR (50)   NULL,
    [ROM]                 VARCHAR (255)  NULL,
    [Delivery]            VARCHAR (255)  NULL,
    [BranchManager]       VARCHAR (255)  NULL,
    [BranchManagerEmail]  VARCHAR (2000) NULL,
    [ROMEmail]            VARCHAR (2000) NULL,
    [WPSite]              VARCHAR (255)  NULL,
    [EmailCC]             VARCHAR (2000) NULL,
    [CPA]                 VARCHAR (50)   NULL,
    [NorthSouth]          VARCHAR (255)  NULL,
    [QualityManager]      VARCHAR (255)  NULL,
    [IsActive]            BIT            NOT NULL,
    [ReportingHierarchy]  VARCHAR (255)  NULL,
    [RegionSES]           VARCHAR (255)  NULL,
    [BranchOwner]         VARCHAR (255)  NOT NULL,
    [FinanceName]         VARCHAR (255)  NULL,
    [BranchManagerEmpNo]  VARCHAR (8)    NULL,
    [WHPLot]              VARCHAR (255)  NULL,
    [DataOwner]           VARCHAR (255)  NOT NULL,
    [ContentHash]         BINARY (32)    NULL,
    [ValidFrom]           DATETIME2 (0)  NULL,
    [ValidTo]             DATETIME2 (0)  NULL,
    [IsCurrent]           BIT            NULL
)
WITH (HEAP, DISTRIBUTION = HASH([DeliverySiteHash]));

