CREATE TABLE [PSA].[Restart_vBIRestart_VacancyInterest] (
    [vai_key]                                 INT            NOT NULL,
    [vacancy_interest_id]                     INT            NULL,
    [vai_vacancy_id]                          INT            NULL,
    [vai_individual_id]                       INT            NULL,
    [vai_engagement_id]                       INT            NULL,
    [vai_date]                                NVARCHAR (12)  NULL,
    [vai_complete_date]                       NVARCHAR (12)  NULL,
    [vai_outcome_1]                           VARCHAR (500)  NULL,
    [vai_outcome_reason]                      VARCHAR (1000) NULL,
    [vai_notes]                               VARCHAR (4000) NULL,
    [vai_acknowledgement_required_by_user_id] INT            NULL,
    [vai_acknowledgement_required]            DATETIME       NULL,
    [vai_stage]                               VARCHAR (250)  NULL,
    [vai_employer_email_sent_date]            NVARCHAR (12)  NULL,
    [vai_proj_id]                             INT            NULL,
    [vai_notification_raised]                 NVARCHAR (12)  NULL,
    [vai_notification_read]                   NVARCHAR (12)  NULL,
    [vai_added_by_user_id]                    INT            NULL,
    [vai_added_date]                          NVARCHAR (12)  NULL,
    [vai_complete_by_user_id]                 INT            NULL,
    [vai_vacancy_external_info_id]            INT            NULL,
    [vai_last_viewed]                         NVARCHAR (12)  NULL,
    [Sys_RunID]                               INT            NULL,
    [Sys_LoadDate]                            DATETIME       NULL,
    [Sys_LoadExpiryDate]                      DATETIME       NULL,
    [Sys_IsCurrent]                           BIT            NULL,
    [Sys_BusKey]                              INT            NULL,
    [Sys_HashKey]                             BINARY (16)    NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

