CREATE TABLE [PSA].[Restart_vBIRestart_Correspondence] (
    [cor_key]                 INT             NOT NULL,
    [correspondence_id]       INT             NULL,
    [cor_date_time]           DATETIME        NULL,
    [cor_duration]            INT             NULL,
    [cor_owner_user_id]       INT             NULL,
    [cor_purpose]             VARCHAR (500)   NULL,
    [cor_purpose_other]       VARCHAR (4000)  NULL,
    [cor_type]                VARCHAR (500)   NULL,
    [cor_recipient]           VARCHAR (500)   NULL,
    [cor_recipient_oth]       VARCHAR (4000)  NULL,
    [cor_successful]          VARCHAR (500)   NULL,
    [cor_notes]               NVARCHAR (4000) NULL,
    [cor_provider_agency_id]  INT             NULL,
    [cor_site_id]             INT             NULL,
    [cor_related_entity_type] VARCHAR (500)   NULL,
    [cor_organisation_id]     INT             NULL,
    [cor_individual_id]       INT             NULL,
    [cor_engagement_id]       INT             NULL,
    [cor_added_date]          DATETIME        NULL,
    [cor_added_by_user_id]    INT             NULL,
    [cor_last_updated_date]   DATETIME        NULL,
    [Sys_RunID]               INT             NULL,
    [Sys_LoadDate]            DATETIME        NULL,
    [Sys_LoadExpiryDate]      DATETIME        NULL,
    [Sys_IsCurrent]           BIT             NULL,
    [Sys_BusKey]              INT             NULL,
    [Sys_HashKey]             BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

