CREATE TABLE [PSA].[Restart_vBIRestart_Meeting] (
    [meet_key]                     INT             NOT NULL,
    [meeting_id]                   INT             NULL,
    [meet_date_time]               DATETIME        NULL,
    [meet_booked_duration]         INT             NULL,
    [meet_type]                    VARCHAR (500)   NULL,
    [meet_type_other]              VARCHAR (1000)  NULL,
    [meet_sub_type]                VARCHAR (500)   NULL,
    [meet_advisor_user_id]         INT             NULL,
    [meet_external_advisor]        VARCHAR (4000)  NULL,
    [meet_location]                VARCHAR (200)   NULL,
    [meet_notes]                   NVARCHAR (4000) NULL,
    [meet_dont_send_reminder]      BIT             NULL,
    [meet_status]                  VARCHAR (500)   NULL,
    [meet_duration]                INT             NULL,
    [meet_related_entity_type]     VARCHAR (12)    NULL,
    [meet_agency_id]               INT             NULL,
    [meet_site_id]                 INT             NULL,
    [meet_engagement_id]           INT             NULL,
    [meet_organisation_id]         INT             NULL,
    [meet_organisation_contact_id] INT             NULL,
    [meet_added_date]              DATETIME        NULL,
    [meet_added_by_user_id]        INT             NULL,
    [meet_complete_date]           DATETIME        NULL,
    [meet_complete_by_user_id]     INT             NULL,
    [meet_mandated]                NVARCHAR (5)    NULL,
    [meet_action_plan_complete]    NVARCHAR (5)    NULL,
    [meet_attendance_reason]       VARCHAR (500)   NULL,
    [meet_attendance_reason_other] NVARCHAR (4000) NULL,
    [meet_last_updated_date]       DATETIME        NULL,
    [meet_rebooked]                VARCHAR(10)     NULL,
    [Sys_RunID]                    INT             NULL,
    [Sys_LoadDate]                 DATETIME        NULL,
    [Sys_LoadExpiryDate]           DATETIME        NULL,
    [Sys_IsCurrent]                BIT             NULL,
    [Sys_BusKey]                   INT             NULL,
    [Sys_HashKey]                  BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

