CREATE TABLE [PSA].[Restart_vBIRestart_Intervention_Service] (
    [isc_key]                               INT             NOT NULL,
    [intervention_service_id]               INT             NULL,
    [isc_title]                             VARCHAR (500)   NULL,
    [isc_source]                            VARCHAR (500)   NULL,
    [isc_source2]                           VARCHAR (500)   NULL,
    [isc_external_partner]                  VARCHAR (500)   NULL,
    [isc_delivery_method]                   NVARCHAR (MAX)  NULL,
    [isc_contact_number]                    VARCHAR (50)    NULL,
    [isc_contact_website]                   VARCHAR (500)   NULL,
    [isc_unit_price]                        VARCHAR (500)   NULL,
    [isc_searchable]                        NVARCHAR (5)    NULL,
    [isc_related_barrier_validation]        VARCHAR (500)   NULL,
    [isc_review_date]                       DATETIME        NULL,
    [isc_description]                       NVARCHAR (4000) NULL,
    [isc_intended_outcomes]                 NVARCHAR (4000) NULL,
    [isc_referral_method]                   NVARCHAR (4000) NULL,
    [isc_duration_of_delivery]              NVARCHAR (500)  NULL,
    [isc_participant_led_delivery_duration] NVARCHAR (5)    NULL,
    [isc_allow_multiple_interventions]      NVARCHAR (5)    NULL,
    [isc_funded_unfunded]                   VARCHAR (500)   NULL,
    [isc_reporting_category]                NVARCHAR (MAX)  NULL,
    [isc_added_date]                        DATETIME        NULL,
    [isc_added_by_user_id]                  INT             NULL,
    [isc_last_updated_date]                 DATETIME        NULL,
    [Sys_RunID]                             INT             NULL,
    [Sys_LoadDate]                          DATETIME        NULL,
    [Sys_LoadExpiryDate]                    DATETIME        NULL,
    [Sys_IsCurrent]                         BIT             NULL,
    [Sys_BusKey]                            INT             NULL,
    [Sys_HashKey]                           BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

