CREATE TABLE [PSA].[Restart_vBIRestart_Intervention] (
    [int_key]                                INT             NOT NULL,
    [intervention_id]                        INT             NULL,
    [int_support_required]                   INT             NULL,
    [int_activity_type]                      VARCHAR (500)   NULL,
    [int_advisor_user_id]                    INT             NULL,
    [int_owner]                              VARCHAR (500)   NULL,
    [int_status]                             VARCHAR (500)   NULL,
    [int_start_date]                         DATE            NULL,
    [int_date_agreed]                        DATE            NULL,
    [int_to_be_completed_by_date]            DATE            NULL,
    [int_personalised_action]                VARCHAR (200)   NULL,
    [int_details_and_objectives]             NVARCHAR (4000) NULL,
    [int_evidence_completion]                VARCHAR (4000)  NULL,
    [int_left_early_withdrawn_reason]        VARCHAR (4000)  NULL,
    [int_end_date]                           DATE            NULL,
    [int_total_duration]                     INT             NULL,
    [int_intervention_service_id]            INT             NULL,
    [int_specialist_location_site_id]        INT             NULL,
    [int_specialist_user_id]                 INT             NULL,
    [int_specialist_referral_form]           INT             NULL,
    [int_specialist_status]                  VARCHAR (500)   NULL,
    [int_specialist_complete_date]           DATE            NULL,
    [int_specialist_method_of_contact]       VARCHAR (500)   NULL,
    [int_specialist_notes]                   VARCHAR (4000)  NULL,
    [int_agency_id]                          INT             NULL,
    [int_site_id]                            INT             NULL,
    [int_engagement_id]                      INT             NULL,
    [int_associated_organisation_id]         INT             NULL,
    [int_associated_organisation_contact_id] INT             NULL,
    [int_added_date]                         DATETIME        NULL,
    [int_added_by_user_id]                   INT             NULL,
    [int_complete_date]                      DATETIME        NULL,
    [int_complete_by_user_id]                INT             NULL,
    [int_last_updated_date]                  DATETIME        NULL,
    [Sys_RunID]                              INT             NULL,
    [Sys_LoadDate]                           DATETIME        NULL,
    [Sys_LoadExpiryDate]                     DATETIME        NULL,
    [Sys_IsCurrent]                          BIT             NULL,
    [Sys_BusKey]                             INT             NULL,
    [Sys_HashKey]                            BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

