CREATE TABLE [PSA].[Restart_vBICommon_Individual] (
    [individual_key]             INT             NOT NULL,
    [individual_id]              INT             NULL,
    [ind_title]                  VARCHAR (500)   NULL,
    [ind_gender]                 VARCHAR (500)   NULL,
    [ind_forename]               VARCHAR (150)   NULL,
    [ind_surname]                VARCHAR (150)   NULL,
    [ind_known_as]               VARCHAR (150)   NULL,
    [ind_address1]               VARCHAR (100)   NULL,
    [ind_address2]               VARCHAR (100)   NULL,
    [ind_address3]               VARCHAR (100)   NULL,
    [ind_county]                 VARCHAR (100)   NULL,
    [ind_town]                   VARCHAR (100)   NULL,
    [ind_postcode]               VARCHAR (50)    NULL,
    [ind_telephone]              VARCHAR (50)    NULL,
    [ind_mobile]                 VARCHAR (50)    NULL,
    [ind_email]                  VARCHAR (100)   NULL,
    [ind_dob]                    DATETIME        NULL,
    [ind_age_when_added]         INT             NULL,
    [ind_natins]                 VARCHAR (50)    NULL,
    [ind_eligibility_status]     VARCHAR (250)   NULL,
    [ind_eligibility_notes]      NVARCHAR (500)  NULL,
    [ind_ethnic_origin]          VARCHAR (1003)  NULL,
    [ind_ethnic_origin_other]    VARCHAR (300)   NULL,
    [ind_sms_opt_out]            BIT             NULL,
    [ind_email_opt_out]          BIT             NULL,
    [ind_valid_sms]              BIT             NULL,
    [ind_leave_message]          BIT             NULL,
    [ind_next_of_kin]            NVARCHAR (4000) NULL,
    [ind_reasonable_adjustments] NVARCHAR (4000) NULL,
    [ind_safeguarding_concerns]  NVARCHAR (4000) NULL,
    [ind_notes]                  NVARCHAR (4000) NULL,
    [ind_preferred_contact]      VARCHAR (500)   NULL,
    [ind_religion]               VARCHAR (250)   NULL,
    [ind_added_date]             DATETIME        NULL,
    [ind_added_by_user_id]       INT             NULL,
    [ind_last_updated_date]      DATETIME        NULL,
    [Sys_RunID]                  INT             NULL,
    [Sys_LoadDate]               DATETIME        NULL,
    [Sys_LoadExpiryDate]         DATETIME        NULL,
    [Sys_IsCurrent]              BIT             NULL,
    [Sys_BusKey]                 INT             NULL,
    [Sys_HashKey]                BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

