CREATE TABLE [PSA].[Restart_vBIRestart_Outcome] (
    [out_key]                         INT             NOT NULL,
    [outcome_id]                      INT             NULL,
    [out_type]                        VARCHAR (500)   NULL,
    [out_type_other]                  VARCHAR (1000)  NULL,
    [out_date]                        DATETIME        NULL,
    [out_advisor_user_id]             INT             NULL,
    [out_notes]                       NVARCHAR (4000) NULL,
    [out_status]                      VARCHAR (500)   NULL,
    [out_follow_up_date]              DATETIME        NULL,
    [out_eng_start_date]              DATETIME        NULL,
    [out_reason_for_leaving]          VARCHAR (250)   NULL,
    [out_reason_for_leaving_other]    VARCHAR (4000)  NULL,
    [out_job_title]                   VARCHAR (500)   NULL,
    [out_job_type]                    VARCHAR (500)   NULL,
    [out_contract_type]               VARCHAR (500)   NULL,
    [out_employee_identifier]         VARCHAR (250)   NULL,
    [out_salary_amount]               MONEY           NULL,
    [out_salary_unit]                 VARCHAR (500)   NULL,
    [out_hrs_per_week]                REAL            NULL,
    [out_duration]                    VARCHAR (250)   NULL,
    [out_job_source]                  VARCHAR (500)   NULL,
    [out_job_source_other]            VARCHAR (4000)  NULL,
    [out_wage_category]               VARCHAR (500)   NULL,
    [out_paid_by]                     VARCHAR (500)   NULL,
    [out_organisation]                VARCHAR (500)   NULL,
    [out_progression_type]            VARCHAR (500)   NULL,
    [out_left_date]                   DATETIME        NULL,
    [out_prap_upload_date]            DATE            NULL,
    [out_provider_agency_id]          INT             NULL,
    [out_site_id]                     INT             NULL,
    [out_engagement_id]               INT             NULL,
    [out_employer_organisation_id]    INT             NULL,
    [out_employer_contact_id]         INT             NULL,
    [out_added_date]                  DATETIME        NULL,
    [out_added_by_user_id]            INT             NULL,
    [out_complete_date]               DATETIME        NULL,
    [out_complete_by_user_id]         INT             NULL,
    [out_salary_actual_date]          VARCHAR (250)   NULL,
    [out_hoursweek_actual_date]       VARCHAR (250)   NULL,
    [out_unit_actual_date]            VARCHAR (250)   NULL,
    [out_vacancy_id]                  INT             NULL,
    [out_vacancy_interest_id]         INT             NULL,
    [out_last_uppdated_date]          DATETIME        NULL,
    [out_verification_date]           DATETIME        NULL,
    [out_verification_status]         VARCHAR(500)    NULL,
    [out_verification_status_details] NVARCHAR(500)   NULL,
    [Sys_RunID]                       INT             NULL,
    [Sys_LoadDate]                    DATETIME        NULL,
    [Sys_LoadExpiryDate]              DATETIME        NULL,
    [Sys_IsCurrent]                   BIT             NULL,
    [Sys_BusKey]                      INT             NULL,
    [Sys_HashKey]                     BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

