CREATE TABLE [PSA].[Restart_vBIRestart_Vacancy] (
    [vacancy_key]                 INT             NOT NULL,
    [vacancy_id]                  INT             NULL,
    [vac_organisation_id]         INT             NULL,
    [vac_type]                    VARCHAR (500)   NULL,
    [vac_theme]                   VARCHAR (500)   NULL,
    [vac_job_title]               VARCHAR (500)   NULL,
    [vac_contract_type]           VARCHAR (500)   NULL,
    [vac_employment_type]         VARCHAR (250)   NULL,
    [vac_hrs_per_week]            VARCHAR (50)    NULL,
    [vac_salary_from]             MONEY           NULL,
    [vac_salary_to]               MONEY           NULL,
    [vac_salary_unit]             VARCHAR (500)   NULL,
    [vac_duration]                VARCHAR (500)   NULL,
    [vac_no_oppor]                INT             NULL,
    [vac_working_pattern]         VARCHAR (2000)  NULL,
    [vac_location]                VARCHAR (2000)  NULL,
    [vac_status]                  VARCHAR (500)   NULL,
    [vac_closing_date]            NVARCHAR (12)   NULL,
    [vac_priority]                VARCHAR (250)   NULL,
    [vac_pre_screening_required]  BIT             NULL,
    [vac_job_description]         VARCHAR (2000)  NULL,
    [vac_person_specification]    VARCHAR (2000)  NULL,
    [vac_skills_required]         VARCHAR (2000)  NULL,
    [vac_application_process]     VARCHAR (2000)  NULL,
    [vac_contact_details]         VARCHAR (2000)  NULL,
    [vac_project_id]              INT             NULL,
    [vac_notes]                   NVARCHAR (2000) NULL,
    [vac_version_no]              INT             NULL,
    [vac_added_by_user_id]        INT             NULL,
    [vac_added_date]              DATETIME        NULL,
    [vac_complete_by_user_id]     INT             NULL,
    [vac_complete_date]           NVARCHAR (12)   NULL,
    [vac_job_broker_managed]      VARCHAR (500)   NULL,
    [vac_account_manager_user_id] INT             NULL,
    [vac_published_by_user_id]    INT             NULL,
    [vac_published_date]          NVARCHAR (12)   NULL,
    [vac_contact]                 INT             NULL,
    [vac_paid_by]                 VARCHAR (500)   NULL,
    [vac_last_updated_date]       DATETIME        NULL,
    [Sys_RunID]                   INT             NULL,
    [Sys_LoadDate]                DATETIME        NULL,
    [Sys_LoadExpiryDate]          DATETIME        NULL,
    [Sys_IsCurrent]               BIT             NULL,
    [Sys_BusKey]                  INT             NULL,
    [Sys_HashKey]                 BINARY (16)     NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

