CREATE TABLE [PSA].[Restart_vBIRestart_Payment] (
    [pay_key]                INT            NOT NULL,
    [payment_id]             INT            NULL,
    [pay_engagement_id]      INT            NULL,
    [pay_agency_id]          INT            NULL,
    [pay_site_id]            INT            NULL,
    [pay_project]            INT            NULL,
    [pay_related_entity_id]  INT            NULL,
    [pay_date]               DATETIME       NULL,
    [pay_bat_id]             INT            NULL,
    [pay_amount]             NVARCHAR (20)  NULL,
    [pay_provider_bat_id]    INT            NULL,
    [pay_provider_amount]    NVARCHAR (20)  NULL,
    [pay_received_date]      DATETIME       NULL,
    [pay_finance_ref_number] VARCHAR (250)  NULL,
    [pay_dwp_payment_level]  VARCHAR (500)  NULL,
    [pay_performance_level]  VARCHAR (500)  NULL,
    [pay_notes]              VARCHAR (4000) NULL,
    [pay_type]               VARCHAR (500)  NULL,
    [pay_category]           VARCHAR (500)  NULL,
    [pay_status]             VARCHAR (500)  NULL,
    [pay_added_date]         DATETIME       NULL,
    [Sys_RunID]              INT            NULL,
    [Sys_LoadDate]           DATETIME       NULL,
    [Sys_LoadExpiryDate]     DATETIME       NULL,
    [Sys_IsCurrent]          BIT            NULL,
    [Sys_BusKey]             INT            NULL,
    [Sys_HashKey]            BINARY (16)    NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

