CREATE TABLE [PSA].[Restart_vBIRestart_GroupSession] (
    [group_session_key]                      INT            NOT NULL,
    [group_session_id]                       INT            NULL,
    [grs_type]                               VARCHAR (500)  NULL,
    [grs_title]                              VARCHAR (50)   NULL,
    [grs_category_1]                         VARCHAR (500)  NULL,
    [grs_category_2]                         VARCHAR (500)  NULL,
    [grs_category_other]                     VARCHAR (200)  NULL,
    [grs_status]                             VARCHAR (500)  NULL,
    [grs_start_date]                         NVARCHAR (12)  NULL,
    [grs_end_date]                           NVARCHAR (12)  NULL,
    [grs_reg_type]                           VARCHAR (500)  NULL,
    [grs_reg_open]                           VARCHAR (500)  NULL,
    [grs_deadline_date_display]              NVARCHAR (12)  NULL,
    [grs_deadline_time]                      VARCHAR (5)    NULL,
    [grs_portal_reg_open]                    VARCHAR (500)  NULL,
    [grs_max_registrations]                  INT            NULL,
    [grs_review_date]                        NVARCHAR (12)  NULL,
    [grs_description]                        VARCHAR (4000) NULL,
    [grs_details_and_objectives]             VARCHAR (4000) NULL,
    [grs_evidence_completion]                VARCHAR (4000) NULL,
    [grs_delivery_method]                    VARCHAR (500)  NULL,
    [grs_location]                           VARCHAR (4000) NULL,
    [grs_organised_1_display]                VARCHAR (500)  NULL,
    [grs_organised_2_display]                VARCHAR (500)  NULL,
    [grs_organiser_type_display]             VARCHAR (500)  NULL,
    [grs_organiser_user_id]                  INT            NULL,
    [grs_organiser_other]                    VARCHAR (100)  NULL,
    [grs_specialist_org_name]                VARCHAR (150)  NULL,
    [grs_delivered_by_display]               VARCHAR (500)  NULL,
    [grs_deliverer_1_display]                VARCHAR (500)  NULL,
    [grs_deliverer_2_display]                VARCHAR (500)  NULL,
    [grs_deliverer_type_display]             VARCHAR (500)  NULL,
    [grs_deliverer_user_fullname]            VARCHAR (101)  NULL,
    [grs_deliverer_other]                    VARCHAR (100)  NULL,
    [grs_deliverer_specialist_org_name]      VARCHAR (150)  NULL,
    [grs_deliverer_specialist_user_fullname] VARCHAR (101)  NULL,
    [grs_org_specialist_user]                VARCHAR (101)  NULL,
    [grs_places_left_display]                INT            NULL,
    [grs_added_by_fullname]                  VARCHAR (101)  NULL,
    [grs_added_date]                         DATETIME       NULL,
    [grs_complete_date]                      DATETIME       NULL,
    [grs_complete_by_date]                   INT            NULL,
    [grs_archive]                            BIT            NULL,
    [grs_last_updated_date]                  DATETIME       NULL,
    [grs_project_id]                         INT            NULL,
    [Sys_RunID]                              INT            NULL,
    [Sys_LoadDate]                           DATETIME       NULL,
    [Sys_LoadExpiryDate]                     DATETIME       NULL,
    [Sys_IsCurrent]                          BIT            NULL,
    [Sys_BusKey]                             INT            NULL,
    [Sys_HashKey]                            BINARY (16)    NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

