CREATE TABLE [PSA].[Restart_vBIRestart_Engagement] (
    [eng_key]                                                                 INT            NOT NULL,
    [engagement_id]                                                           INT            NULL,
    [eng_tran_id]                                                             INT            NULL,
    [eng_advisor_acknowledgement_required]                                    DATETIME       NULL,
    [eng_start_date]                                                          DATETIME       NULL,
    [eng_exit_date]                                                           DATETIME       NULL,
    [eng_left_date]                                                           DATETIME       NULL,
    [eng_did_not_start_date]                                                  DATETIME       NULL,
    [eng_exit_reason]                                                         VARCHAR (500)  NULL,
    [eng_exit_reason_other]                                                   VARCHAR (500)  NULL,
    [eng_onward_destination]                                                  VARCHAR (500)  NULL,
    [eng_onward_destination_other]                                            VARCHAR (500)  NULL,
    [eng_left_reason]                                                         VARCHAR (500)  NULL,
    [eng_left_reason_other]                                                   VARCHAR (500)  NULL,
    [eng_left_stage]                                                          VARCHAR (500)  NULL,
    [eng_left_stage_other]                                                    VARCHAR (500)  NULL,
    [eng_did_not_start_reason]                                                VARCHAR (500)  NULL,
    [eng_did_not_start_reason_other]                                          NVARCHAR (500) NULL,
    [eng_signed_privacy_notice_uploaded]                                      VARCHAR (500)  NULL,
    [eng_privacy_rights_exercised]                                            VARCHAR (500)  NULL,
    [eng_privacy_rights_details]                                              VARCHAR (500)  NULL,
    [eng_caseload_review_date]                                                DATETIME       NULL,
    [eng_disengaged_date]                                                     DATETIME       NULL,
    [eng_disengaged_reason]                                                   VARCHAR (500)  NULL,
    [eng_frequency_of_contact]                                                VARCHAR (500)  NULL,
    [eng_referral_notes]                                                      VARCHAR (4000) NULL,
    [eng_referral_source]                                                     VARCHAR (500)  NULL,
    [eng_referral_source_other]                                               VARCHAR (250)  NULL,
    [eng_info_employability_referrer_name]                                    NVARCHAR (500) NULL,
    [eng_tran_owner_user_id]                                                  INT            NULL,
    [eng_tran_individual_id]                                                  INT            NULL,
    [eng_tran_date]                                                           DATETIME       NULL,
    [eng_tran_added_date]                                                     DATETIME       NULL,
    [eng_tran_site_id]                                                        INT            NULL,
    [eng_tran_status_1]                                                       VARCHAR (500)  NULL,
    [eng_provider_name]                                                       VARCHAR (100)  NULL,
    [eng_follow_up_date]                                                      DATETIME       NULL,
    [eng_outcome]                                                             VARCHAR (500)  NULL,
    [eng_info_employability_contract_area]                                    VARCHAR (500)  NULL,
    [eng_info_employability_jcp_district]                                     VARCHAR (500)  NULL,
    [eng_info_employability_jcp_office]                                       VARCHAR (500)  NULL,
    [eng_info_employability_referral_date]                                    DATETIME       NULL,
    [eng_info_employability_prap_po_no]                                       VARCHAR (50)   NULL,
    [eng_info_employability_prap_admin_info]                                  VARCHAR (500)  NULL,
    [eng_info_employability_prap_acknowledge_date]                            DATETIME       NULL,
    [eng_info_employability_prap_start_acknowledge_date]                      DATETIME       NULL,
    [eng_info_employability_prap_dna_acknowledge_date]                        DATETIME       NULL,
    [eng_info_employability_prap_early_leaver_acknowledge_date]               DATETIME       NULL,
    [eng_info_employability_referrer_email]                                   NVARCHAR (500) NULL,
    [eng_info_employability_induction_pack_issued]                            NVARCHAR (5)   NULL,
    [eng_info_employability_last_job_readiness_review]                        DATETIME       NULL,
    [eng_info_employability_universal_cred_receipt]                           NVARCHAR (5)   NULL,
    [eng_info_employability_sustained_earnings]                               NVARCHAR (5)   NULL,
    [eng_info_employability_right_to_work]                                    NVARCHAR (5)   NULL,
    [eng_info_employability_reside_in_england_wales]                          NVARCHAR (5)   NULL,
    [eng_info_employability_working_age]                                      NVARCHAR (5)   NULL,
    [eng_info_employability_not_taking_dwp_employment]                        NVARCHAR (5)   NULL,
    [eng_info_employability_not_in_control_group_or_public_sector_comparator] NVARCHAR (5)   NULL,
    [eng_info_employability_exoffender]                                       NVARCHAR (5)   NULL,
    [eng_info_employability_consider_themselves_disabled]                     NVARCHAR (5)   NULL,
    [eng_info_employability_initial_eligibility_confirmed]                    NVARCHAR (5)   NULL,
    [eng_job_readiness]                                                       VARCHAR (500)  NULL,
    [eng_info_employability_employment_interests]                             NVARCHAR (MAX) NULL,
    [eng_info_employability_last_updated_date]                                DATETIME       NULL,
    [Sys_RunID]                                                               INT            NULL,
    [Sys_LoadDate]                                                            DATETIME       NULL,
    [Sys_LoadExpiryDate]                                                      DATETIME       NULL,
    [Sys_IsCurrent]                                                           BIT            NULL,
    [Sys_BusKey]                                                              INT            NULL,
    [Sys_HashKey]                                                             BINARY (16)    NULL
)
WITH (CLUSTERED INDEX([Sys_BusKey]), DISTRIBUTION = HASH([Sys_BusKey]));

