CREATE VIEW [ICONI].[SAT_Employee_Iconi_Core] AS SELECT 
CONCAT_WS('|','ICONI',E.[user_id]) AS EmployeeKey,
E.user_fullname AS EmployeeFullName,
E.user_forename AS EmployeeFirstName,
E.user_surname AS EmployeeLastName,
E.user_agency_id AS EmployeeAgency,
E.user_email AS EmployeeEmail,
E.user_suspended_date AS EmployeeSuspendedDate,
E.user_type AS EmployeeType,
E.user_organisation_id AS EmployeeOrganisation,
E.user_added_date AS EmployeeAddedDate,
E.user_username AS EmployeeUsername,
E.user_supports_over_50 AS EmployeeSupportsOver50,
E.user_locked AS EmployeeLocked,
E.user_sso_identifier AS EmployeeSsoIdentifier,
E.user_sso_enabled AS EmployeeSsoEnabled,
E.role_name AS EmployeeJobTitle,
E.user_notes AS EmployeeNotes,
E.user_last_login AS EmployeeLastLogin,
E.user_archive AS EmployeeArchive,
E.user_timeout_timer AS EmployeeTimeoutTimer,
E.user_licencing_prog AS EmployeeLicencingProg,
E.user_last_updated_date AS EmployeeLastUpdatedDate,
E.ValidFrom,
E.ValidTo,
E.IsCurrent
FROM [ICONI].[vBICommon_User] as E;
