# ------------------------------------------------------------------------------
# Author    : Kishore Kumar Nagisetty
# GitHub    : https://github.com/kishorenagisetty
# Project   : Azure Synapse ADF Deployment using Terraform
# Created   : 2024-06-25
# License   : MIT
# ------------------------------------------------------------------------------
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# trigger:
# - main

pool:
  name: Azure Pipelines
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
