CREATE VIEW [dwh].[dim_WorkflowEventsDrillThroughEmployee] AS select		cas.RecordSource
			,cas.CaseHashBin
			,cas.CaseHash
			,cas.ParticipantHash
			,cas.EmployeeHash
			,cas.ReferralHashBin
			,cas.ReferralHash
			,cas.ProgrammeHash
			,cas.DeliverySiteHash
			,cas.ReferralDate
			,cas.ReferralType
			,cas.StartDate
			,cas.StartMonth
			,cas.StartVerifiedDate
			,cas.LeaveDate
			,cas.ProjectedLeaveDate
			,cas.ReportDate
			,cas.ReferralSLADate
			,cas.FirstJobStartDate
			,cas.JobOutcomeOneClaimedDate
			,cas.JobOutcomeOneClaimedDate_IsDWP
			,cas.JobOutcomeOneClaimedDate_NotDWP
			,cas.JobLeaveAddDate
			--,cas.JobLeaveAddDateMonthYear
			--,cas.SDMonthFirstJob
			--,cas.SDMonthJobOutcome
			--,cas.SDMonthFirstEarning
			,cas.ProjectedOutcomeDate
			,cas.CaseID
			,cas.CaseOutcomeStatus
			--,cas.CaseStatusHash
			,cas.CaseStatus
			--,cas.WorkRedinessStatus
			--,cas.RequestorHash
			--,cas.RowNumber
			,cas.IsDisengaged
			--,cas.WasDisengaged
			--,cas.InitialAppointmentNotCompleted
			--,cas.EngagementStatus
			--,cas.OffTrack
			--,cas.IsRapidResponce
			--,cas.NoCorrespondenceWelcomePack
			--,cas.NoActionPlan
			--,cas.FirstCorrespondenceDate
			--,cas.LastCorrespondenceDate
			--,cas.LastCorrespondenceStatus
			--,cas.OnTrackStatus
			--,cas.CurrentStage
			--,cas.CumulativeEarningsToDate
			--,cas.RemainingEarnings
			,cas.CaseAdvisorName
			,cas.LastJobAssignmentTitle
			,cas.LastJobAssignmentStartDate
			--,cas.LastJobWeeklyHours
			--,cas.LastJobContractedHours
			--,cas.LastJobEmploymentSiteName
			,cas.LastJobLeaveDate
			--,cas.DaysSinceReferral
			,par.ParticipantID
			,del.DeliverySiteName
			,del.ReportingZone
from		dwh.fact_Case			cas
left join	dwh.dim_Participant		par on par.ParticipantHash = cas.ParticipantHash
left join	dwh.dim_DeliverySite	del on del.DeliverySiteHash = cas.DeliverySiteHash;