CREATE VIEW [dwh].[fact_CaseDrillThrough] AS select		cas.CaseHash
			,cast(cas.CaseID as varchar(250))							as CaseID
			,cast(cas.ReferralDate as varchar(250))						as ReferralDate
			,cast(cas.ReferralType as varchar(250))						as ReferralType
			,cast(cas.StartDate as varchar(250))						as StartDate
			,cast(cas.StartMonth as varchar(250))						as StartMonth
			,cast(cas.StartVerifiedDate as varchar(250))				as StartVerifiedDate
			,cast(cas.LeaveDate as varchar(250))						as LeaveDate
			,cast(cas.ProjectedLeaveDate as varchar(250))				as ProjectedLeaveDate
			,cast(cas.ReportDate as varchar(250))						as ReportDate
			,cast(cas.ReferralSLADate as varchar(250))					as ReferralSLADate
			,cast(cas.FirstJobStartDate as varchar(250))				as FirstJobStartDate
			,cast(cas.JobOutcomeOneClaimedDate as varchar(250))			as JobOutcomeOneClaimedDate
			,cast(cas.JobOutcomeOneClaimedDate_IsDWP as varchar(250))	as JobOutcomeOneClaimedDate_IsDWP
			,cast(cas.JobOutcomeOneClaimedDate_NotDWP as varchar(250))	as JobOutcomeOneClaimedDate_NotDWP
			,cast(cas.JobLeaveAddDate as varchar(250))					as JobLeaveAddDate
			,cast(cas.JobLeaveAddDateMonthYear as varchar(250))			as JobLeaveAddDateMonthYear
			,cast(cas.SDMonthFirstJob as varchar(250))					as SDMonthFirstJob
			,cast(cas.SDMonthJobOutcome as varchar(250))				as SDMonthJobOutcome
			,cast(cas.SDMonthFirstEarning as varchar(250))				as SDMonthFirstEarning
			,cast(cas.ProjectedOutcomeDate as varchar(250))				as ProjectedOutcomeDate
			,cast(cas.CaseIDNumber as varchar(250))						as CaseIDNumber
			,cast(cas.CaseOutcomeStatus as varchar(250))				as CaseOutcomeStatus
			,cast(cas.CaseStatus as varchar(250))						as CaseStatus
			,cast(cas.WorkRedinessStatus as varchar(250))				as WorkRedinessStatus
			,cast(cas.LeaveReason as varchar(250))						as LeaveReason
			--cast(cas.RequestorHash as varchar(250))					as RequestorHash
			,cast(cas.RowNumber as varchar(250))						as RowNumber
			,cast(cas.IsDisengaged as varchar(250))						as IsDisengaged
			,cast(cas.IsDisengagedDate as varchar(250))					as IsDisengagedDate
			,cast(cas.WasDisengaged as varchar(250))					as WasDisengaged
			,cast(cas.InitialAppointmentNotCompleted as varchar(250))	as InitialAppointmentNotCompleted
			,cast(cas.InitialAppointmentBooked as varchar(250))			as InitialAppointmentBooked
			,cast(cas.InitialAppointmentBookedDate as varchar(250))		as InitialAppointmentBookedDate
			,cast(cas.InitialAppointmentCompletedDate as varchar(250))	as InitialAppointmentCompletedDate
			,cast(cas.EngagementStatus as varchar(250))					as EngagementStatus
			,cast(cas.OffTrack as varchar(250))							as OffTrack
			,cast(cas.IsRapidResponce as varchar(250))					as IsRapidResponce
			,cast(cas.NoCorrespondenceWelcomePack as varchar(250))		as NoCorrespondenceWelcomePack
			,cast(cas.NoActionPlan as varchar(250))						as NoActionPlan
			,cast(cas.FirstCorrespondenceDate as varchar(250))			as FirstCorrespondenceDate
			,cast(cas.LastCorrespondenceDate as varchar(250))			as LastCorrespondenceDate
			,cast(cas.LastCorrespondanceToToday as varchar(250))		as LastCorrespondanceToToday
			,cast(cas.LastCorrespondenceStatus as varchar(250))			as LastCorrespondenceStatus
			,cast(cas.OnTrackStatus as varchar(250))					as OnTrackStatus
			,cast(cas.CurrentStage as varchar(250))						as CurrentStage
			,cast(cas.CumulativeEarningsToDate as varchar(250))			as CumulativeEarningsToDate
			,cast(cas.RemainingEarnings as varchar(250))				as RemainingEarnings
			,cast(cas.CaseAdvisorName as varchar(250))					as CaseAdvisorName
			,cast(cas.LastJobAssignmentTitle as varchar(250))			as LastJobAssignmentTitle
			,cast(cas.LastJobAssignmentStartDate as varchar(250))		as LastJobAssignmentStartDate
			,cast(cas.LastJobWeeklyHours as varchar(250))				as LastJobWeeklyHours
			,cast(cas.LastJobContractedHours as varchar(250))			as LastJobContractedHours
			,cast(cas.LastJobEmploymentSiteName as varchar(250))		as LastJobEmploymentSiteName
			,cast(cas.LastJobClaimDate as varchar(250))					as LastJobClaimDate
			,cast(cas.LastJobLeaveDate as varchar(250))					as LastJobLeaveDate
			,cast(cas.FirstJobAssignmentTitle as varchar(250))			as FirstJobAssignmentTitle
			,cast(cas.FirstJobWeeklyHours as varchar(250))				as FirstJobWeeklyHours
			,cast(cas.FirstJobContractedHours as varchar(250))			as FirstJobContractedHours
			,cast(cas.FirstJobEmploymentSiteName as varchar(250))		as FirstJobEmploymentSiteName
			,cast(cas.FirstJobClaimDate as varchar(250))				as FirstJobClaimDate
			,cast(cas.FirstJobLeaveDate as varchar(250))				as FirstJobLeaveDate
			,cast(cas.DaysSinceReferral as varchar(250))				as DaysSinceReferral
			,cast(cas.ExitReportUploadedDate as varchar(250))			as ExitReportUploadedDate
from		dwh.fact_case cas;