CREATE EXTERNAL FILE FORMAT [TextFileFormat]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'|', DATE_FORMAT = N'dd/MM/yyyy', FIRST_ROW = 2, ENCODING = N'UTF8')
    );

