CREATE TABLE [DW].[F_AtW_Work_Flow_Event_Analysis] (
    [Work_Flow_Events_Skey]                          INT      NOT NULL,
    [WorkFlowStages_Skey]                            INT      NULL,
    [WorkFlowEventType_Skey]                         INT      NULL,
    [WorkFlowEventDate_Skey]                         INT      NULL,
    [WorkFlowEventTime_Skey]                         INT      NULL,
    [WorkFlowEstimatedStartDate_Skey]                INT      NULL,
    [WorkFlowEstimatedStartTime_Skey]                INT      NULL,
    [WorkFlowEstimatedEndDate_Skey]                  INT      NULL,
    [WorkFlowEstimatedEndTime_Skey]                  INT      NULL,
    [WorkFlowOriginalStartDate_Skey]                 INT      NULL,
    [WorkFlowOriginalStartTime_Skey]                 INT      NULL,
    [WorkFlowEndDate_Skey]                           INT      NULL,
    [WorkFlowEndTime_Skey]                           INT      NULL,
    [WorkFlowEventEmployee_Skey]                     INT      NULL,
    [WorkFlowEventEmployeeHistory_Skey]              INT      NULL,
    [Case_Analysis_Skey]                             INT      NULL,
    [Candidate_Skey]                                 INT      NULL,
    [Case_Skey]                                      INT      NULL,
    [Source_Skey]                                    INT      NULL,
    [Case_Status_Skey]                               INT      NULL,
    [Programme_Skey]                                 INT      NULL,
    [CaseCreatedDate_Skey]                           INT      NULL,
    [CaseCreatedTime_Skey]                           INT      NULL,
    [CaseReceivedDate_Skey]                          INT      NULL,
    [CaseReceivedTime_Skey]                          INT      NULL,
    [PredictedEndDate_Skey]                          INT      NULL,
    [PredictedEndTime_Skey]                          INT      NULL,
    [ApprovedDate_Skey]                              INT      NULL,
    [ApprovedTime_Skey]                              INT      NULL,
    [CaseClosedDate_Skey]                            INT      NULL,
    [CaseClosedTime_Skey]                            INT      NULL,
    [CasePlanActiveDate_Skey]                        INT      NULL,
    [CasePlanActiveTime_Skey]                        INT      NULL,
    [Employer_Contact_Skey]                          INT      NULL,
    [Employer_Skey]                                  INT      NULL,
    [Attrition_Reason_Skey]                          INT      NULL,
    [CaseOwnerEmp_Skey]                              INT      NULL,
    [CaseOwnerEmpHist_Skey]                          INT      NULL,
    [CurrentStage_Skey]                              INT      NULL,
    [AttritionStage_Skey]                            INT      NULL,
    [AttritionDate_Skey]                             INT      NULL,
    [AttritionTime_Skey]                             INT      NULL,
    [NewEnquiry]                                     INT      NOT NULL,
    [ReferralCallRequired]                           INT      NOT NULL,
    [ReferralCallBackAttempt1]                       INT      NOT NULL,
    [ReferralCallBackAttempt2]                       INT      NOT NULL,
    [ReferralCallBackAttempt3]                       INT      NOT NULL,
    [LiveEnquiry]                                    INT      NOT NULL,
    [UnsuccessfulEnquiry]                            INT      NOT NULL,
    [SuccessfulEnquiry]                              INT      NOT NULL,
    [AwaitingReferral]                               INT      NOT NULL,
    [ReferralReceived]                               INT      NOT NULL,
    [EmailreferraltoDWP]                             INT      NOT NULL,
    [ReferralApproved]                               INT      NOT NULL,
    [ReferralUnsuccessful]                           INT      NOT NULL,
    [InitialContact]                                 INT      NOT NULL,
    [AwaitingTelephoneAssessmentMeetingSchedule]     INT      NOT NULL,
    [TelephoneAssessmentscheduled]                   INT      NOT NULL,
    [TelephoneAssessmentCompleted]                   INT      NOT NULL,
    [AwaitingSupportPlanmeetingscheduled]            INT      NOT NULL,
    [Supportplanmeetingscheduled]                    INT      NOT NULL,
    [Supportplanmeetingcompleted]                    INT      NOT NULL,
    [Supportplansignedbycustomer]                    INT      NOT NULL,
    [SupportplanUploaded]                            INT      NOT NULL,
    [SupportplancompletedbutnotsubmittedtoDWP]       INT      NOT NULL,
    [SupportplansubmittedtoDWP]                      INT      NOT NULL,
    [SupportPlanNotApprovedbyDWP]                    INT      NOT NULL,
    [AwaitingSupportPlanReSubmission]                INT      NOT NULL,
    [SupportPlanReSubmitted]                         INT      NOT NULL,
    [SupportplanapprovedbyDWP]                       INT      NOT NULL,
    [SupportplanpaidbyDWP]                           INT      NOT NULL,
    [Month1updateoutstanding]                        INT      NOT NULL,
    [Month1updatecompleted]                          INT      NOT NULL,
    [Month1BOTUpdateCompleted]                       INT      NOT NULL,
    [Month1updatesubmittedtoDWP]                     INT      NOT NULL,
    [Month2updateoutstanding]                        INT      NOT NULL,
    [Month2updatecompleted]                          INT      NOT NULL,
    [Month2BOTUpdateCompleted]                       INT      NOT NULL,
    [Month2updatesubmittedtoDWP]                     INT      NOT NULL,
    [Month3updateoutstanding]                        INT      NOT NULL,
    [Month3updatecompleted]                          INT      NOT NULL,
    [Month3BOTUpdateCompleted]                       INT      NOT NULL,
    [Month3updatesubmittedtoDWP]                     INT      NOT NULL,
    [Month4updateoutstanding]                        INT      NOT NULL,
    [Month4updatecompleted]                          INT      NOT NULL,
    [Month4BOTUpdateCompleted]                       INT      NOT NULL,
    [Month4updatesubmittedtoDWP]                     INT      NOT NULL,
    [Month5updateoutstanding]                        INT      NOT NULL,
    [Month5updatecompleted]                          INT      NOT NULL,
    [Month5BOTUpdateCompleted]                       INT      NOT NULL,
    [Month5updatesubmittedtoDWP]                     INT      NOT NULL,
    [Awaiting6MonthSupportPlanmeetingscheduled]      INT      NOT NULL,
    [Month6Supportplanmeetingscheduled]              INT      NOT NULL,
    [Month6Supportplanmeetingcompleted]              INT      NOT NULL,
    [Month6Supportplansignedbycustomer]              INT      NOT NULL,
    [Month6SupportplanUploaded]                      INT      NOT NULL,
    [Month6SupportplancompletedbutnotsubmittedtoDWP] INT      NOT NULL,
    [Month6SupportplansubmittedtoDWP]                INT      NOT NULL,
    [Month6SupportPlanNotApprovedbyDWP]              INT      NOT NULL,
    [AwaitingMonth6SupportPlanReSubmission]          INT      NOT NULL,
    [Month6SupportPlanReSubmitted]                   INT      NOT NULL,
    [Month6SupportplanapprovedbyDWP]                 INT      NOT NULL,
    [Month6SupportplanpaidbyDWP]                     INT      NOT NULL,
    [AwaitingTransferToBSC]                          INT      NOT NULL,
    [TransferredToBSC]                               INT      NOT NULL,
    [LightTouchEmailSentUnsuccessful]                INT      NOT NULL,
    [LightTouchEmailSentSuccessful]                  INT      NOT NULL,
    [AwaitingMonth7Contact]                          INT      NOT NULL,
    [Month7ContactSuccessful]                        INT      NOT NULL,
    [Month7ContactUnsuccessful]                      INT      NOT NULL,
    [AwaitingMonth8Contact]                          INT      NOT NULL,
    [Month8ContactSuccessful]                        INT      NOT NULL,
    [Month8ContactUnsuccessful]                      INT      NOT NULL,
    [Awaiting9MonthReportmeetingscheduled]           INT      NOT NULL,
    [NineMonthReportmeetingscheduled]                INT      NOT NULL,
    [NineMonthReportmeetingcompleted]                INT      NOT NULL,
    [NineMonthReportsignedbycustomer]                INT      NOT NULL,
    [NineMonthReportUploaded]                        INT      NOT NULL,
    [NineMonthReportcompletedbutnotsubmittedtoDWP]   INT      NOT NULL,
    [NineMonthReportsubmittedtoDWP]                  INT      NOT NULL,
    [NineMonthReportNotApprovedbyDWP]                INT      NOT NULL,
    [Awaiting9MonthReportReSubmission]               INT      NOT NULL,
    [NineMonthReportReSubmitted]                     INT      NOT NULL,
    [NineMonthReportapprovedbyDWP]                   INT      NOT NULL,
    [NineMonthReportpaidbyDWP]                       INT      NOT NULL,
    [Rejected]                                       INT      NOT NULL,
    [EventCount]                                     INT      NOT NULL,
    [EventOutstandingCount]                          INT      NOT NULL,
    [EventCompletedCount]                            INT      NOT NULL,
    [EventOverDueCount]                              INT      NOT NULL,
    [EventCompletedWithinSLACount]                   INT      NOT NULL,
    [EventCompletedOutsideSLACount]                  INT      NOT NULL,
    [EventSkippedCount]                              INT      NULL,
    [MarketingCampaignAttempted]                     INT      NOT NULL,
    [Month7ContactAttempted]                         INT      NOT NULL,
    [Month8ContactAttempted]                         INT      NOT NULL,
    [Month1UpdateSuccessful]                         INT      NOT NULL,
    [Month2UpdateSuccessful]                         INT      NOT NULL,
    [Month3UpdateSuccessful]                         INT      NOT NULL,
    [Month4UpdateSuccessful]                         INT      NOT NULL,
    [Month5UpdateSuccessful]                         INT      NOT NULL,
    [Sys_LoadDate]                                   DATETIME NULL,
    [Sys_RunID]                                      INT      NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Case_Analysis_Skey]));







