CREATE TABLE [DW].[F_AtW_Work_Flow_Stage_Analysis] (
    [Work_Flow_Stages_Skey]             INT NOT NULL,
    [Stage_Skey]                        INT NULL,
    [WorkFlowStartDate_Skey]            INT NULL,
    [WorkFlowStartTime_Skey]            INT NULL,
    [WorkFlowEndDate_Skey]              INT NULL,
    [WorkFlowEndTime_Skey]              INT NULL,
    [Candidate_Skey]                    INT NULL,
    [Case_Skey]                         INT NULL,
    [Source_Skey]                       INT NULL,
    [Case_Status_Skey]                  INT NULL,
    [Programme_Skey]                    INT NULL,
    [CaseCreatedDate_Skey]              INT NULL,
    [CaseCreatedTime_Skey]              INT NULL,
    [CaseReceivedDate_Skey]             INT NULL,
    [CaseReceivedTime_Skey]             INT NULL,
    [PredictedEndDate_Skey]             INT NULL,
    [PredictedEndTime_Skey]             INT NULL,
    [ApprovedDate_Skey]                 INT NULL,
    [ApprovedTime_Skey]                 INT NULL,
    [CaseClosedDate_Skey]               INT NULL,
    [CaseClosedTime_Skey]               INT NULL,
    [CasePlanActiveDate_Skey]           INT NULL,
    [CasePlanActiveTime_Skey]           INT NULL,
    [Employer_Contact_Skey]             INT NULL,
    [Employer_Skey]                     INT NULL,
    [Attrition_Reason_Skey]             INT NULL,
    [CaseOwnerEmp_Skey]                 INT NULL,
    [CaseOwnerEmpHist_Skey]             INT NULL,
    [CurrentStage_Skey]                 INT NULL,
    [AttritionStage_Skey]               INT NULL,
    [AttritionDate_Skey]                INT NULL,
    [AttritionTime_Skey]                INT NULL,
    [MonthlyActivityOutstanding]        INT NULL,
    [MonthlyActivityComplete]           INT NULL,
    [MA_Month6or9MeetingScheduled]      INT NULL,
    [DaysToCompleteMonthlyActivity]     INT NULL,
    [MonthlyActivityCompleteWithinSLA]  INT NULL,
    [MonthlyActivityCompleteOutsideSLA] INT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Case_Skey]));



