CREATE TABLE [DW].[F_Case_Analysis] (
    [Case_Analysis_Skey]              INT      NOT NULL,
    [CaseBusKey]                      INT      NULL,
    [Candidate_Skey]                  INT      NULL,
    [Case_Skey]                       INT      NULL,
    [Source_Skey]                     INT      NULL,
    [Case_Status_Skey]                INT      NULL,
    [Programme_Skey]                  INT      NULL,
    [CaseCreatedDate_Skey]            INT      NULL,
    [CaseCreatedTime_Skey]            INT      NULL,
    [CaseReceivedDate_Skey]           INT      NULL,
    [CaseReceivedTime_Skey]           INT      NULL,
    [PredictedEndDate_Skey]           INT      NULL,
    [PredictedEndTime_Skey]           INT      NULL,
    [ApprovedDate_Skey]               INT      NULL,
    [ApprovedTime_Skey]               INT      NULL,
    [CaseClosedDate_Skey]             INT      NULL,
    [CaseClosedTime_Skey]             INT      NULL,
    [CasePlanActiveDate_Skey]         INT      NULL,
    [CasePlanActiveTime_Skey]         INT      NULL,
    [Employer_Contact_Skey]           INT      NULL,
    [Employer_Skey]                   INT      NULL,
    [Attrition_Reason_Skey]           INT      NULL,
    [CaseOwnerEmp_Skey]               INT      NULL,
    [CaseOwnerEmpHist_Skey]           INT      NULL,
    [CaseCount]                       INT      NOT NULL,
    [CurrentStage_Skey]               INT      NULL,
    [AttritionStage_Skey]             INT      NULL,
    [AttritionDate_Skey]              INT      NULL,
    [AttritionTime_Skey]              INT      NULL,
    [AttritionCount]                  INT      NOT NULL,
    [AttritionHistoryCount]           INT      NULL,
    [AttritionDisengagedCount]        INT      NOT NULL,
    [AttritionDisengagedHistoryCount] INT      NULL,
    [AttritionLeftJobCount]           INT      NOT NULL,
    [AttritionLeftJobHistoryCount]    INT      NULL,
    [AttritionCovidCount]             INT      NOT NULL,
    [AttritionCovidHistoryCount]      INT      NULL,
    [SuspendedCount]                  INT      NOT NULL,
    [ActiveCount]                     INT      NOT NULL,
    [Sys_LoadDate]                    DATETIME NULL,
    [Sys_RunID]                       INT      NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([Case_Skey]));



