CREATE TABLE [ELT].[DQ_Exception_Area] (
    [DqExceptionAreaID] INT            IDENTITY (1, 1) NOT NULL,
    [Exception_Area]    VARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_CTL_DqExceptionArea] PRIMARY KEY NONCLUSTERED ([DqExceptionAreaID] ASC) NOT ENFORCED
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

