CREATE TABLE [ELT].[DQ_Exception_Type] (
    [DqExceptionTypeID] INT            IDENTITY (1, 1) NOT NULL,
    [Exception_Type]    VARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_CTL_DqExceptionType] PRIMARY KEY NONCLUSTERED ([DqExceptionTypeID] ASC) NOT ENFORCED
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

