CREATE TABLE [ELT].[HMRC]
(
	[DATE CREATED] [nvarchar](255) NULL,
	[REFERRAL NUMBER] [nvarchar](255) NULL,
	[NINO] [nvarchar](255) NULL,
	[NOTIFICATION TYPE] [nvarchar](255) NULL,
	[NOTIFICATION DATE] [nvarchar](255) NULL,
	[SOURCE SYSTEM] [nvarchar](255) NULL,
	[SUPPLIER NAME] [nvarchar](255) NULL,
	[SUPPLIER SITE CODE] [nvarchar](255) NULL,
	[CPA] [float] NULL,
	[RECORD STATUS] [nvarchar](255) NULL,
	[ASN CREATION STATUS] [nvarchar](255) NULL,
	[ASN NUMBER] [nvarchar](255) NULL,
	[INVOICE NUMBER] [nvarchar](255) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN)
GO