CREATE EXTERNAL TABLE [ext].[D_Date] (
    [Date_Skey] INT NOT NULL,
    [Date] VARCHAR (50) NULL,
    [Full_Date] VARCHAR (50) NULL,
    [Date_Description] VARCHAR (50) NULL,
    [Full_Date_Description] VARCHAR (100) NULL,
    [Day_Of_Month] INT NULL,
    [Day_Of_Month_Suffix] VARCHAR (50) NULL,
    [Day_Name_Short] VARCHAR (50) NULL,
    [Day_Name_Long] VARCHAR (50) NULL,
    [Week_Code] VARCHAR (50) NULL,
    [Week_Number] INT NULL,
    [Week_Number_Full] VARCHAR (50) NULL,
    [Month_Code] VARCHAR (50) NULL,
    [Month_Name_Short] VARCHAR (50) NULL,
    [Month_Name_Long] VARCHAR (50) NULL,
    [Month_Number] INT NULL,
    [Month_Number_Full] VARCHAR (50) NULL,
    [Quarter_Code] VARCHAR (50) NULL,
    [Quarter_Number] INT NULL,
    [Quarter_Short_Name] VARCHAR (50) NULL,
    [Quarter_Long_Name] VARCHAR (50) NULL,
    [Semester_Code] VARCHAR (50) NULL,
    [Semester_Number] INT NULL,
    [Semester_Short_Name] VARCHAR (50) NULL,
    [Semester_Long_Name] VARCHAR (50) NULL,
    [Year_Code] VARCHAR (50) NULL,
    [Year_Number] INT NULL,
    [Year_Name] VARCHAR (50) NULL,
    [Report_Period] INT NULL,
    [Rolling_Week] INT NULL,
    [Day_Reverse_Count_Key] INT NULL,
    [Day_Count_Key] INT NULL,
    [Fiscal_Year] INT NULL,
    [Fiscal_Year_Name] VARCHAR (50) NULL,
    [Fiscal_Semester_Number] INT NULL,
    [Fiscal_Semester_Short_Name] VARCHAR (50) NULL,
    [Fiscal_Semester_Long_Name] VARCHAR (50) NULL,
    [Fiscal_Quarter_Number] INT NULL,
    [Fiscal_Quarter_Short_Name] VARCHAR (50) NULL,
    [Fiscal_Quarter_Full_Name] VARCHAR (50) NULL,
    [Fiscal_Month_Number] INT NULL,
    [Fiscal_Month_Full_Name] VARCHAR (50) NULL,
    [Is_Calendar_Month_End] INT NULL,
    [Is_Accounting_Month_End] INT NULL,
    [Is_Calendar_Quarter_End] INT NULL,
    [Is_Calendar_Year_End] INT NULL,
    [Is_Accounting_Year_End] INT NULL,
    [Is_Business_Day] INT NULL,
    [Is_Holiday] INT NULL,
    [Is_Weekend] INT NULL,
    [Savings_Week] VARCHAR (50) NULL,
    [Active_Performance_Period] INT NULL,
    [End_Of_Week_Date] VARCHAR (50) NULL,
    [Month_Year_Name] VARCHAR (50) NULL,
    [Day_Of_Month_Reversed] INT NULL,
    [CHDA_Contract_Year_Code] VARCHAR (50) NULL,
    [CHDA_Contract_Year_Number] INT NULL,
    [CHDA_Contract_Year_Name] VARCHAR (25) NULL,
    [CHDA_Contract_Month_Code] VARCHAR (50) NULL,
    [CHDA_Contract_Month_Number_Full] VARCHAR (50) NULL,
    [CHDA_Contract_Month_Number] INT NULL,
    [Year_Month_Number] INT NULL,
    [Year_Quarter_Number] INT NULL,
    [CHDA_Contract_Year_Month_Number] INT NULL,
    [CHDA_Contract_Year_Quarter_Number] INT NULL,
    [Previous_Year_Month_Number] INT NULL,
    [Business_Day_Of_Month] INT NULL,
    [Business_Day_Of_Month_Reversed] INT NULL,
    [Business_Days_In_Month] INT NULL,
    [End_Of_Week_Date_Sunday] VARCHAR (50) NULL,
    [Non_Business_Days_In_Month] INT NULL,
    [Is_Business_Day_Scotland] INT NULL,
    [Is_Holiday_Scotland] INT NULL,
    [Business_Day_Of_Month_Scotland] INT NULL,
    [Business_Day_Of_Month_Reversed_Scotland] INT NULL,
    [Business_Days_In_Month_Scotland] INT NULL,
    [Non_Business_Days_In_Month_Scotland] INT NULL,
    [Holiday_Year] VARCHAR (50) NULL,
    [Fiscal_Week_Number] INT NULL,
    [Calendar_Reporting_Month_Name] VARCHAR (50) NULL,
    [Calendar_Reporting_Week_Number] INT NULL,
    [Fiscal_Week_Number_In_Month] INT NULL,
    [Fiscal_Month_Name] VARCHAR (50) NULL
)
    WITH (
    DATA_SOURCE = [polybasestaging],
    LOCATION = N'D_Date/',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



