CREATE TABLE [LZ].[AtW_vw_cm_case] (
    [caseId]                 INT           NULL,
    [providerId]             INT           NULL,
    [mainProcessId]          INT           NULL,
    [caseComplexityId]       INT           NULL,
    [caseServiceSourceId]    INT           NULL,
    [caseStatusId]           INT           NULL,
    [folderId]               INT           NULL,
    [vrcUserId]              VARCHAR (255) NULL,
    [otherServiceSource]     VARCHAR (255) NULL,
    [caseSourceId]           INT           NULL,
    [isCustomerSelfEmployed] BIT           NULL,
    [caseReceivedDate]       DATETIME      NULL,
    [prapDate]               DATETIME      NULL,
    [attendingWork]          BIT           NULL,
    [jobType]                VARCHAR (255) NULL,
    [hoursWorked]            INT           NULL,
    [isVeteranCase]          BIT           NULL,
    [isReCase]               BIT           NULL,
    [isCloseCase]            BIT           NULL,
    [providerComment]        VARCHAR (11)  NULL,
    [isDirectCase]           BIT           NULL,
    [disclosedMHToEmployer]  BIT           NULL,
    [predictedEndDate]       DATETIME      NULL,
    [closedDate]             DATETIME      NULL,
    [createdDate]            DATETIME      NULL,
    [createdBy]              VARCHAR (255) NULL,
    [lastModifiedDate]       DATETIME      NULL,
    [lastModifiedBy]         VARCHAR (255) NULL,
    [active]                 BIT           NULL,
    [enquiryReceivedDate]    DATETIME      NULL,
    [Sys_RunID]              INT           NULL,
    [Sys_LoadDate]           DATETIME      NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

