CREATE TABLE [ADAPT].[LK_RegionZones] (
    [Zone]                  NVARCHAR (255) NULL,
    [Reporting_Region]      NVARCHAR (255) NULL,
    [Reporting_Area_Branch] NVARCHAR (255) NULL,
    [Reporting_Zone]        NVARCHAR (255) NULL,
    [Baan_Region]           INT            NULL,
    [Baan_Area_Branch]      INT            NULL,
    [Baan_Zone]             VARCHAR (10)   NULL,
    [DS_Region]             INT            NULL,
    [TempID]                INT            NULL,
    [Ofsted]                VARCHAR (50)   NULL,
    [ROM]                   VARCHAR (255)  NULL,
    [Delivery]              VARCHAR (255)  NULL,
    [CoreProvider]          VARCHAR (255)  NULL,
    [ID]                    BIGINT         NOT NULL,
    [BranchManager]         VARCHAR (255)  NULL,
    [BranchManagerEmail]    VARCHAR (2000) NULL,
    [ROM_Email]             VARCHAR (2000) NULL,
    [WPSite]                VARCHAR (255)  NULL,
    [Email_CC]              VARCHAR (2000) NULL,
    [CPA]                   VARCHAR (50)   NULL,
    [NorthSouth]            VARCHAR (255)  NULL,
    [QualityManager]        VARCHAR (255)  NULL,
    [IsActive]              BIT            NOT NULL,
    [Reporting_Hierarchy]   VARCHAR (255)  NULL,
    [Region_SES]            VARCHAR (255)  NULL,
    [BranchOwner]           VARCHAR (255)  NOT NULL,
    [FinanceName]           VARCHAR (255)  NULL,
    [BranchManagerEmpNo]    VARCHAR (8)    NULL,
    [WHPLot]                VARCHAR (255)  NULL,
    [DataOwner]             VARCHAR (255)  NOT NULL
)
WITH (HEAP, DISTRIBUTION = REPLICATE);

