CREATE VIEW [BV].[SAT_AssignmentEarningPattern_Core] AS select 
[AssignmentEarningPatternHash] AS [AssignmentEarningPatternHash]
,[AssignmentHash] AS [AssignmentHash]
      ,[EarningsKey]
      ,[AssignmentKey]
      ,[Program]
      ,[SalaryUnit]
      ,[HourlyRate]
      ,[EarningPatternDaysPerWeek]
      ,[MonthOfYear]
      ,[DailyHours]
      ,[EarningsToDate]
      ,[HoursPerWeek]
      ,[DayOfWeek]
      ,[DayNumber]
      ,[DailyRate]
      ,[DailyRateType]
      ,[EffectFrom]
      ,[EffectTo]
      ,[Days]
      ,[JobStartDate]
      ,[JobLeaveDate]
      ,[IsFurlough]
      ,[CaseEarningstoDateBracket]
      ,[CaseHMRCEarningsBracket]
      ,[PredictedJobOutcomeDate]
      ,[CaseEarningsAtTrackingEnd]
from [BV].[SAT_AssignmentEarningPattern_Adapt_Core]
union all
select 
[AssignmentEarningPatternHash] AS [AssignmentEarningPatternHash]
,[AssignmentHash] AS [AssignmentHash]
      ,[AssignmentEarningPatternKey]
      ,[AssignmentKey]
      ,[Programme]
      ,[EarningPatternPaymentFrequency]
      ,[EarningPatternPaymentAmount]
      ,[EarningPatternDaysPerWeek]
      ,[MonthOfYear]
      ,[EarningPatternDailyHours]
      ,[EarningsToDate]
      ,[EarningPatternWeeklyHours]
      ,[EarningsPatternDayOfWeek]
      ,[DayNumber]
      ,[EarningPatternDailyRate]
      ,[EarningPatternDailyRateType]
      ,[EarningPatternEffectiveFrom]
      ,[EarningPatternEffectiveTo]
      ,[EarningPatternDays]
      ,[JobStartDate]
      ,[JobLeaveDate]
      ,[IsFurlough]
      ,[CaseEarningstoDateBracket]
      ,[CaseHMRCEarningsBracket]
      ,[PredictedJobOutcomeDate]
      ,[CaseEarningsAtTrackingEnd]
from [BV].[SAT_AssignmentEarningPattern_Iconi_Core];
GO


