CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_X_CUST_ANSR] (
    [BISUNIQUEID] BIGINT NULL,
    [OCC_ID] DECIMAL (20) NULL,
    [ADD_NOTES] NVARCHAR (MAX) NULL,
    [MANDATORY] NVARCHAR (MAX) NULL,
    [QUESTION] NVARCHAR (MAX) NULL,
    [ASSESSMENT] DECIMAL (16) NULL,
    [ANSWER] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_X_CUST_ANSR/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



