CREATE EXTERNAL TABLE [DELTA].[ADAPT_MD_MULTI_NAMES] (
    [ID] BIGINT NULL,
    [TYPE] NVARCHAR (MAX) NULL,
    [LANGUAGE] INT NULL,
    [NAME] NVARCHAR (MAX) NULL,
    [DESCRIPTION] NVARCHAR (MAX) NULL,
    [ICON_FILE_NAME] NVARCHAR (MAX) NULL,
    [SVG_FILE_NAME] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/MD_MULTI_NAMES/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



