CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_CAND_PREF] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [SMOKING_ENV] NVARCHAR (MAX) NULL,
    [PART_TIME] NVARCHAR (MAX) NULL,
    [OPT_OUT_WTD] NVARCHAR (MAX) NULL,
    [RATE_REQ] DECIMAL (8, 2) NULL,
    [SALARY_REQ] DECIMAL (8, 2) NULL,
    [OTE_REQ] DECIMAL (8, 2) NULL,
    [LOCATION] NVARCHAR (MAX) NULL,
    [P_TEMP] NVARCHAR (MAX) NULL,
    [P_PERM] NVARCHAR (MAX) NULL,
    [P_CONTR] NVARCHAR (MAX) NULL,
    [RATETYPE_REQ] DECIMAL (20) NULL,
    [RELOCATE] NVARCHAR (MAX) NULL,
    [LOOK_FOR] NVARCHAR (MAX) NULL,
    [SALARY_DES] DECIMAL (8, 2) NULL,
    [RATE_DES] DECIMAL (8, 2) NULL,
    [CONTACT] NVARCHAR (MAX) NULL,
    [DISTANCE] DECIMAL (8, 2) NULL,
    [HOURS_PREF] DECIMAL (8, 2) NULL,
    [CONTACTABLE] DECIMAL (20) NULL,
    [HOURS_TO] DECIMAL (8, 2) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_CAND_PREF/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



