CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_SHORT_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [DATE_SHORT] DATETIME2 (0) NULL,
    [TIME_SHORT] DATETIME2 (0) NULL,
    [STATUS] DECIMAL (20) NULL,
    [LAST_CV_DT] DATETIME2 (0) NULL,
    [LAST_CV_TM] DATETIME2 (0) NULL,
    [LAST_IV_DT] DATETIME2 (0) NULL,
    [LAST_IV_TM] DATETIME2 (0) NULL,
    [SHORT_BY] DECIMAL (16) NULL,
    [SHORT_ID] DECIMAL (16) NULL,
    [LAST_CV_BY] DECIMAL (16) NULL,
    [LAST_IV_BY] DECIMAL (16) NULL,
    [LAST_OF_DT] DATETIME2 (0) NULL,
    [LAST_OF_TM] DATETIME2 (0) NULL,
    [LAST_OF_BY] DECIMAL (16) NULL,
    [OFFER_SAL] DECIMAL (11, 2) NULL,
    [REJ_OF_DT] DATETIME2 (0) NULL,
    [REJ_OF_TM] DATETIME2 (0) NULL,
    [REJ_OF_BY] DECIMAL (16) NULL,
    [REJ_DT] DATETIME2 (0) NULL,
    [REJ_TM] DATETIME2 (0) NULL,
    [REJ_BY] DECIMAL (16) NULL,
    [ASSIG_DATE] DATETIME2 (0) NULL,
    [LAST_IV_ST] DECIMAL (20) NULL,
    [REJECTED_BY] DECIMAL (20) NULL,
    [LONGLISTED] NVARCHAR (MAX) NULL,
    [SH_VIA_STAGE] NVARCHAR (MAX) NULL,
    [REJ_RSN] DECIMAL (20) NULL,
    [REJ_OFF_RSN] DECIMAL (20) NULL,
    [REJ_REASON] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_SHORT_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



