CREATE EXTERNAL TABLE [DELTA].[ADAPT_MD_NAMED_OCCS] (
    [OCC_ID] BIGINT NULL,
    [CONFIG_NAME] NVARCHAR (MAX) NULL,
    [OWNER_ID] BIGINT NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/MD_NAMED_OCCS/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



