CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_DSUB_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [TITLE] NVARCHAR (MAX) NULL,
    [COMPANY] DECIMAL (16) NULL,
    [CONTACT] DECIMAL (16) NULL,
    [PHONE] DECIMAL (20) NULL,
    [INT_DATE1] DATETIME2 (0) NULL,
    [INT_DATE2] DATETIME2 (0) NULL,
    [INT_DATE3] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_DSUB_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



