CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_BARRIER_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [START_DT] DATETIME2 (0) NULL,
    [END_DT] DATETIME2 (0) NULL,
    [PRIORITY] DECIMAL (20) NULL,
    [STATUS] DECIMAL (20) NULL,
    [NAME] NVARCHAR (MAX) NULL,
    [BARRIER] DECIMAL (20) NULL,
    [BARRIER_TYPE] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_BARRIER_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



