CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_PERSON_GEN_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [TITLE] DECIMAL (20) NULL,
    [FIRST_NAME] NVARCHAR (MAX) NULL,
    [MIDDLE_NAME] NVARCHAR (MAX) NULL,
    [LAST_NAME] NVARCHAR (MAX) NULL,
    [FULLNAME] NVARCHAR (MAX) NULL,
    [SALUTATION] NVARCHAR (MAX) NULL,
    [PERSON_ID] DECIMAL (16) NULL,
    [INITIALS] NVARCHAR (MAX) NULL,
    [RES_POOL] NVARCHAR (MAX) NULL,
    [JOB_FAMILY] DECIMAL (20) NULL,
    [HR_CONS] DECIMAL (16) NULL,
    [COR_LANG] DECIMAL (20) NULL,
    [CUR_EMPL] DECIMAL (16) NULL,
    [ESS_QCHECK] DATETIME2 (0) NULL,
    [OFFLIMIT] NVARCHAR (MAX) NULL,
    [ESS_AUTHCHCK] DATETIME2 (0) NULL,
    [DT_OF_BIRTH] DATETIME2 (0) NULL,
    [UNDO] NVARCHAR (MAX) NULL,
    [PRAP] NVARCHAR (MAX) NULL,
    [IMPORT_DT] DATETIME2 (0) NULL,
    [PRAP_STATUS] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_PERSON_GEN/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

