CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_EQUAL_GEN_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [GENDER] DECIMAL (20) NULL,
    [DISABILITY] NVARCHAR (MAX) NULL,
    [MARITAL_STAT] DECIMAL (20) NULL,
    [ETHNIC_ORIG] DECIMAL (20) NULL,
    [EQUAL_ID] DECIMAL (16) NULL,
    [CANDIDATE] DECIMAL (16) NULL,
    [RELIGION] DECIMAL (20) NULL,
    [DISAB_CODE] DECIMAL (20) NULL,
    [SEXUAL_ORIEN] DECIMAL (20) NULL,
    [OUT_OF_WORK] DECIMAL (20) NULL,
    [TRANS_AVAIL] NVARCHAR (MAX) NULL,
    [COST_TRANS] NVARCHAR (MAX) NULL,
    [TRAVEL_COMM] NVARCHAR (MAX) NULL,
    [COMMNCTN_ND] NVARCHAR (MAX) NULL,
    [EDU_QUALS] NVARCHAR (MAX) NULL,
    [CARING_RESP] NVARCHAR (MAX) NULL,
    [ETHNIC_DET] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_EQUAL_GEN/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

