CREATE EXTERNAL TABLE [DELTA].[ADAPT_DOCUMENT_TEMPLATES] (
    [DOC_TEMPLATE_ID] BIGINT NULL,
    [CONFIG_NAME] NVARCHAR (MAX) NULL,
    [CREATED_DATE] DATETIME2 (0) NULL,
    [CREATED_BY] BIGINT NULL,
    [UPDATED_DATE] DATETIME2 (0) NULL,
    [UPDATED_BY] BIGINT NULL,
    [DOC_TYPE_ID] BIGINT NULL,
    [LAST_USED_DATE] DATETIME2 (0) NULL,
    [OWNER_TYPE] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/DOCUMENT_TEMPLATES/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



