CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_TELEPHONE] (
    [BISUNIQUEID] BIGINT NULL,
    [OCC_ID] DECIMAL (16) NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [TEL_NUMBER] NVARCHAR (MAX) NULL,
    [EXTENSION] NVARCHAR (MAX) NULL,
    [CAN_CONTACT] NVARCHAR (MAX) NULL,
    [CAN_SMS] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_TELEPHONE/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



