CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_RTE_HRS_HIST_History] (
    [BISUNIQUEID] BIGINT NULL,
    [EFFECT_TO] DATETIME2 (0) NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [FRI] DECIMAL (4, 2) NULL,
    [MON] DECIMAL (4, 2) NULL,
    [SAT] DECIMAL (4, 2) NULL,
    [SUN] DECIMAL (4, 2) NULL,
    [THU] DECIMAL (4, 2) NULL,
    [TUE] DECIMAL (4, 2) NULL,
    [WED] DECIMAL (4, 2) NULL,
    [WEEKLY_HRS] DECIMAL (5, 2) NULL,
    [EFFECT_FROM] DATETIME2 (0) NULL,
    [HOURLY_RATE] DECIMAL (11, 2) NULL,
    [STATUS] DECIMAL (20) NULL,
    [DATE_CHANGED] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_RTE_HRS_HIST/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

