CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_WP_COM_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [NOTES] NVARCHAR (MAX) NULL,
    [CONT_BY] DECIMAL (16) NULL,
    [OUTCOME] DECIMAL (20) NULL,
    [METHOD] DECIMAL (20) NULL,
    [COM_DATE] DATETIME2 (0) NULL,
    [DIS_FOLLOWUP] DECIMAL (20) NULL,
    [COMTYPE] DECIMAL (20) NULL,
    [ACTIVITY] DECIMAL (16) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_WP_COM/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

