CREATE EXTERNAL TABLE [DELTA].[ADAPT_vw_Documents_PSA_History] (
    [DOC_ID] DECIMAL (16) NULL,
    [OWNER_ID] BIGINT NULL,
    [DOC_CATEGORY] BIGINT NULL,
    [DOC_NAME] NVARCHAR (MAX) NULL,
    [DOC_DESCRIPTION] NVARCHAR (MAX) NULL,
	[DOCUMENT] NVARCHAR (MAX) NULL,
    [FILE_EXTENSION] NVARCHAR (MAX) NULL,
    [CREATED_DATE] DATETIME2 (0) NULL,
    [CREATED_BY] DECIMAL (18) NULL,
    [UPDATED_BY] DECIMAL (18) NULL,
    [UPDATED_DATE] DATETIME2 (0) NULL,
    [NOTES] NVARCHAR (MAX) NULL,
    [DEFAULT] NVARCHAR (MAX) NULL,
    [SIZE] DECIMAL (16) NULL,
    [STATUS] NVARCHAR (MAX) NULL,
    [OWNER_TYPE] NVARCHAR (MAX) NULL,
    [PREVIEW_TYPE] NVARCHAR (MAX) NULL,
    [MODIFY_DATE] DATETIME2 (0) NULL,
    [PREVIEW_UPD_DATE] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR(MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/vw_Documents_PSA/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

