CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_PJOB_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [HOURS_TYPE] DECIMAL (20) NULL,
    [FIX_TERM] NVARCHAR (MAX) NULL,
    [SAL_FROM] DECIMAL (11, 2) NULL,
    [SAL_TO] DECIMAL (11, 2) NULL,
    [OTE] DECIMAL (8, 2) NULL,
    [OPEN_SINCE] DATETIME2 (0) NULL,
    [NOT_PERIOD] DECIMAL (20) NULL,
    [EDUC_LEVEL] DECIMAL (20) NULL,
    [TEMP_REQ] NVARCHAR (MAX) NULL,
    [PAY_INT] NVARCHAR (MAX) NULL,
    [SAL_REV] DATETIME2 (0) NULL,
    [ASALARY] NVARCHAR (MAX) NULL,
    [NO_REQ] DECIMAL (3) NULL,
    [SAL_VAL1] DECIMAL (8, 2) NULL,
    [SAL_VAL2] DECIMAL (8, 2) NULL,
    [NO_MONTHS] NVARCHAR (MAX) NULL,
    [NO_SOFAR] DECIMAL (3) NULL,
    [RENUMUNIT] DECIMAL (20) NULL,
    [EXT_FILLED] DECIMAL (3) NULL,
    [NO_REMAIN] DECIMAL (3) NULL,
    [TEMPPERM] DECIMAL (20) NULL,
    [WAGE_CAT] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_PJOB_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



