CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_ACTION_GEN_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [ACT_TYPE] DECIMAL (20) NULL,
    [SIGNED] NVARCHAR (MAX) NULL,
    [STATUS] DECIMAL (20) NULL,
    [ADD_DATE] DATETIME2 (0) NULL,
    [COMPL_DATE] DATETIME2 (0) NULL,
    [OPEN_A_COUNT] DECIMAL (10) NULL,
    [CLOSED_A_CNT] DECIMAL (10) NULL,
    [FRT_ACTIV_SD] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_ACTION_GEN/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

