CREATE EXTERNAL TABLE [DELTA].[adapt_JOURNAL_ENTRIES] (
    [ID] DECIMAL (16) NULL,
    [CREATION_DATE] DATETIME2 (0) NULL,
    [CREATOR_ID] BIGINT NULL,
    [BO_ID] BIGINT NULL,
    [ENTITY_ID_1] BIGINT NULL,
    [ENTITY_ID_2] BIGINT NULL,
    [ENTITY_ID_3] BIGINT NULL,
    [ENTITY_ID_4] BIGINT NULL,
    [ENTITY_ID_5] BIGINT NULL,
    [ENTITY_ID_6] BIGINT NULL,
    [ROLE_ID_1] BIGINT NULL,
    [ROLE_ID_2] BIGINT NULL,
    [ROLE_ID_3] BIGINT NULL,
    [ROLE_ID_4] BIGINT NULL,
    [ROLE_ID_5] BIGINT NULL,
    [ROLE_ID_6] BIGINT NULL,
    [J_NOTES] NVARCHAR (MAX) NULL,
    [J_DOCUMENT] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/JOURNAL_ENTRIES/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

