CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_JOB_HIST_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [FILLED_DT] DATETIME2 (0) NULL,
    [FILLED_TM] DATETIME2 (0) NULL,
    [NO_CV_SENT] DECIMAL (4) NULL,
    [NO_IV_ARR] DECIMAL (4) NULL,
    [NO_IV_ATT] DECIMAL (4) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_JOB_HIST/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

