CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_X_WP_GRADING] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [GRADING] DECIMAL (20) NULL,
    [EMPLOYEE] DECIMAL (16) NULL,
    [DATE_CHANGE] DATETIME2 (0) NULL,
    [TIME_CHANGE] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_X_WP_GRADING/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



