CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_ASSESS_CUST] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [RESULT] NVARCHAR (MAX) NULL,
    [ACCURACY] NVARCHAR (MAX) NULL,
    [CUSTOMER] DECIMAL (16) NULL,
    [DATE_TAKEN] DATETIME2 (0) NULL,
    [ASSESS_TYPE] DECIMAL (20) NULL,
    [SELF_EFF] NVARCHAR (MAX) NULL,
    [PULSE] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_ASSESS_CUST/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



