CREATE EXTERNAL TABLE [DELTA].[ADAPT_CODE_GROUP_INDEX] (
    [GROUP_ID] BIGINT NULL,
    [CONFIG_DISPLAY_NAME] NVARCHAR (MAX) NULL,
    [FORMAT] NVARCHAR (MAX) NULL,
    [LOCKED_DOWN] NVARCHAR (MAX) NULL,
    [LOOKUP_BY] NVARCHAR (MAX) NULL,
    [SORT_ORDER] NVARCHAR (MAX) NULL,
    [NODES_EXPANDED] NVARCHAR (MAX) NULL,
    [ALLOW_PARENT_SELECTION] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/CODE_GROUP_INDEX/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



