CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_SOC_IMP_HIST] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [Q1_ANSWER] DECIMAL (20) NULL,
    [Q2_ANSWER] DECIMAL (20) NULL,
    [Q3_ANSWER] DECIMAL (20) NULL,
    [Q4_ANSWER] DECIMAL (20) NULL,
    [Q5_ANSWER] DECIMAL (20) NULL,
    [Q6_ANSWER] DECIMAL (20) NULL,
    [Q7_ANSWER] DECIMAL (20) NULL,
    [TOTAL] DECIMAL (2) NULL,
    [COLOR] NVARCHAR (MAX) NULL,
    [ANSWER_DATE] DATETIME2 (0) NULL,
    [Q8_ANSWER] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_SOC_IMP_HIST/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

