CREATE EXTERNAL TABLE [DELTA].[ADAPT_BUSINESS_OBJECTS] (
    [BO_ID] BIGINT NULL,
    [CATEGORY_ID] BIGINT NULL,
    [CONFIG_NAME] NVARCHAR (MAX) NULL,
    [SECURITY_LEVEL] DECIMAL (18) NULL,
    [VERSION_NUMBER] INT NULL,
    [CREATED_BY] BIGINT NULL,
    [CREATED_DATE] DATETIME2 (0) NULL,
    [UPDATED_BY] BIGINT NULL,
    [UPDATED_DATE] DATETIME2 (0) NULL,
    [LOCKED_DOWN] NVARCHAR (MAX) NULL,
    [PREVIEW] NVARCHAR (MAX) NULL,
    [JAVA_BO] NVARCHAR (MAX) NULL,
    [LEGACY_CLASS] VARBINARY (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/BUSINESS_OBJECTS/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



