CREATE EXTERNAL TABLE [DELTA].[ADAPT_MD_ROLES_History] (
    [ROLE_ID] BIGINT NULL,
    [PARENT_ID] BIGINT NULL,
    [CONFIG_ROLE_NAME] NVARCHAR (MAX) NULL,
    [READ_ACCESS] INT NULL,
    [MODIFY_ACCESS] INT NULL,
    [DELETE_ACCESS] INT NULL,
    [LOCKED_DOWN] NVARCHAR (MAX) NULL,
    [ROLE_TYPE] NVARCHAR (MAX) NULL,
    [DEFAULT_ATTRIB1] NVARCHAR (MAX) NULL,
    [DEFAULT_ATTRIB2] NVARCHAR (MAX) NULL,
    [DEFAULT_ATTRIB3] NVARCHAR (MAX) NULL,
    [ALLOWS_DUMMY] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/MD_ROLES/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

