CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_ASSIG_FEE] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [SALARY] DECIMAL (11, 2) NULL,
    [FEE] DECIMAL (8, 2) NULL,
    [FEE_TYPE] DECIMAL (20) NULL,
    [CRED_AMOUNT] DECIMAL (8, 2) NULL,
    [REAS_CREDIT] DECIMAL (20) NULL,
    [FEE_PERC] DECIMAL (5, 2) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_ASSIG_FEE/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



