CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_JOB_JOBBOARD] (
    [BISUNIQUEID] BIGINT NULL,
    [PRIMREF] DECIMAL (16) NULL,
    [JOB_TITLE] NVARCHAR (MAX) NULL,
    [SALARY_FROM] DECIMAL (11, 2) NULL,
    [SALARY_TO] DECIMAL (11, 2) NULL,
    [RATE_FROM] DECIMAL (7, 2) NULL,
    [RATE_TO] DECIMAL (7, 2) NULL,
    [EMAIL_RESP] NVARCHAR (MAX) NULL,
    [LOCATION] NVARCHAR (MAX) NULL,
    [EXP_TO_HOME] NVARCHAR (MAX) NULL,
    [EXP_TO_JB] NVARCHAR (MAX) NULL,
    [VALID_FROM] DATETIME2 (0) NULL,
    [VALID_T0] DATETIME2 (0) NULL,
    [AUTH] NVARCHAR (MAX) NULL,
    [CONTACT_USER] NVARCHAR (MAX) NULL,
    [EMAIL] NVARCHAR (MAX) NULL,
    [START_DATE] DATETIME2 (0) NULL,
    [END_DATE] DATETIME2 (0) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_JOB_JOBBOARD/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



