CREATE EXTERNAL TABLE [DELTA].[ADAPT_ENTITY_TABLE_History] (
    [ENTITY_ID] DECIMAL (16) NULL,
    [STATUS] NVARCHAR (MAX) NULL,
    [CREATEDDATE] DATETIME2 (0) NULL,
    [CREATED_BY] BIGINT NULL,
    [UPDATEDDATE] DATETIME2 (0) NULL,
    [UPDATED_BY] BIGINT NULL,
    [DELETEDDATE] DATETIME2 (0) NULL,
    [DELETED_BY] BIGINT NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/ENTITY_TABLE/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );


GO

