CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_EMPLOYEE_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [USER_REF] DECIMAL (16) NULL,
    [PAYROLL] NVARCHAR (MAX) NULL,
    [LST_ACT_DT] DATETIME2 (0) NULL,
    [NAME] NVARCHAR (MAX) NULL,
    [EMPLOY_TYPE] DECIMAL (20) NULL,
    [APP_ID] DECIMAL (10) NULL,
    [EMAIL] NVARCHAR (MAX) NULL,
    [JOB_TITLE] NVARCHAR (MAX) NULL,
    [STATUS] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_EMPLOYEE_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    )
    ;



