CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_ADDRESS_History] (
    [BISUNIQUEID] BIGINT NULL,
    [OCC_ID] DECIMAL (16) NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [STREET1] NVARCHAR (MAX) NULL,
    [STREET2] NVARCHAR (MAX) NULL,
    [LOCALITY] NVARCHAR (MAX) NULL,
    [TOWN] NVARCHAR (MAX) NULL,
    [COUNTY] NVARCHAR (MAX) NULL,
    [POST_CODE] NVARCHAR (MAX) NULL,
    [COUNTRY] DECIMAL (20) NULL,
    [MAP] NVARCHAR (MAX) NULL,
    [SEARCHLOC] DECIMAL (16) NULL,
    [POSTCODEAREA] DECIMAL (20) NULL,
    [DISTRICT] DECIMAL (20) NULL,
    [SECTOR] DECIMAL (20) NULL,
    [TIMEZONE] DECIMAL (20) NULL,
    [REGION] DECIMAL (16) NULL,
    [STREET3] NVARCHAR (MAX) NULL,
    [NORTHING] DECIMAL (12, 8) NULL,
    [EASTING] DECIMAL (12, 8) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_ADDRESS/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

