CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_DISABILITY] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [DISABILITY] DECIMAL (20) NULL,
    [DISLEVEL] DECIMAL (20) NULL,
    [CONTRACT] DECIMAL (16) NULL,
    [PRIMARY_YN] NVARCHAR (MAX) NULL,
    [PRIMARY_DIS] DECIMAL (20) NULL,
    [AREA] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_DISABILITY/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



