CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_JOB_BEN_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [DRESS_CODE] DECIMAL (20) NULL,
    [SMOK_ENV] NVARCHAR (MAX) NULL,
    [W_HOURS] DECIMAL (20) NULL,
    [HOL_ENT] DECIMAL (3) NULL,
    [PEN_INF] DECIMAL (20) NULL,
    [HEALTH_INS] NVARCHAR (MAX) NULL,
    [OVER_INF] NVARCHAR (MAX) NULL,
    [LIFE_ASSUR] NVARCHAR (MAX) NULL,
    [BONUS_INF] NVARCHAR (MAX) NULL,
    [ON_SITE_PARK] NVARCHAR (MAX) NULL,
    [OTHER] NVARCHAR (MAX) NULL,
    [SEAS_PEAKS] NVARCHAR (MAX) NULL,
    [AW_HOURS] NVARCHAR (MAX) NULL,
    [TRANSPORT] DECIMAL (20) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_JOB_BEN/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

