CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_IV_GEN] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [IV_CONT] DECIMAL (16) NULL,
    [STAGE] DECIMAL (20) NULL,
    [IV_DATE] DATETIME2 (0) NULL,
    [IV_START] DATETIME2 (0) NULL,
    [IV_END] DATETIME2 (0) NULL,
    [IV_ID] DECIMAL (16) NULL,
    [FEEDBACK] NVARCHAR (MAX) NULL,
    [IV_ATT] NVARCHAR (MAX) NULL,
    [FEEDBACK_CAN] NVARCHAR (MAX) NULL,
    [FEEDBACK_CLT] NVARCHAR (MAX) NULL,
    [F_IV_CHB] NVARCHAR (MAX) NULL,
    [SE_IV_CHB] NVARCHAR (MAX) NULL,
    [TH_IV_CHB] NVARCHAR (MAX) NULL,
    [FOUR_IV_CHB] NVARCHAR (MAX) NULL,
    [FIFTH_IV_CHB] NVARCHAR (MAX) NULL,
    [NO_SHOW] NVARCHAR (MAX) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_IV_GEN/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



