CREATE EXTERNAL TABLE [DELTA].[ADAPT_PROP_DOCTRACK_GEN_History] (
    [BISUNIQUEID] BIGINT NULL,
    [REFERENCE] DECIMAL (16) NULL,
    [DOCNAME] NVARCHAR (MAX) NULL,
    [RECEIVER] DECIMAL (16) NULL,
    [RECEIVED_DT] DATETIME2 (0) NULL,
    [SENT_DT] DATETIME2 (0) NULL,
    [RESENT_DT] DATETIME2 (0) NULL,
    [STATUS] DECIMAL (20) NULL,
    [COMPLETED_BY] DECIMAL (16) NULL,
    [COMPLETED_DT] DATETIME2 (0) NULL,
    [QUERIED_BY] DECIMAL (16) NULL,
    [QUERIED_DT] DATETIME2 (0) NULL,
    [NOTES] NVARCHAR (MAX) NULL,
    [SENDER] DECIMAL (16) NULL,
    [RESENDER] DECIMAL (16) NULL,
    [ID] DECIMAL (16) NULL,
    [ATTACHED] NVARCHAR (MAX) NULL,
    [ARCHIVED] NVARCHAR (MAX) NULL,
    [JOB_REF] DECIMAL (16) NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/PROP_DOCTRACK_GEN/IsCurrent=false',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

