CREATE EXTERNAL TABLE [DELTA].[ADAPT_DOCUMENT_CATEGORIES] (
    [CATEGORY_ID] BIGINT NULL,
    [PARENT_ID] BIGINT NULL,
    [SEARCHABLE] NVARCHAR (MAX) NULL,
    [READ_ACCESS] INT NULL,
    [MODIFY_ACCESS] INT NULL,
    [DELETE_ACCESS] INT NULL,
    [LOCKED_DOWN] NVARCHAR (MAX) NULL,
    [CONFIG_NAME] NVARCHAR (MAX) NULL,
    [DOC_CONTENT_LIMIT_SIZE] DECIMAL (10, 2) NULL,
    [IS_DIRTY] NVARCHAR (MAX) NULL,
    [GROUP_ID] BIGINT NULL,
    [ValidFrom] DATETIME2 (0) NULL,
    [ValidTo] DATETIME2 (0) NULL,
    [row_sha2] NVARCHAR (MAX) NULL
)
    WITH (
    DATA_SOURCE = [ADLG2_PSA],
    LOCATION = N'delta/ADAPT/DOCUMENT_CATEGORIES/IsCurrent=true',
    FILE_FORMAT = [parquet_file_format],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );



