CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_Intervention_Service]
(
	[intervention_service_id] [int] NULL,
	[isc_title] [nvarchar](max) NULL,
	[isc_source] [nvarchar](max) NULL,
	[isc_source2] [nvarchar](max) NULL,
	[isc_external_partner] [nvarchar](max) NULL,
	[isc_delivery_method] [nvarchar](max) NULL,
	[isc_contact_number] [nvarchar](max) NULL,
	[isc_contact_website] [nvarchar](max) NULL,
	[isc_unit_price] [nvarchar](max) NULL,
	[isc_searchable] [nvarchar](max) NULL,
	[isc_related_barrier_validation] [nvarchar](max) NULL,
	[isc_review_date] [datetime2](0) NULL,
	[isc_description] [nvarchar](max) NULL,
	[isc_intended_outcomes] [nvarchar](max) NULL,
	[isc_referral_method] [nvarchar](max) NULL,
	[isc_duration_of_delivery] [nvarchar](max) NULL,
	[isc_participant_led_delivery_duration] [nvarchar](max) NULL,
	[isc_allow_multiple_interventions] [nvarchar](max) NULL,
	[isc_funded_unfunded] [nvarchar](max) NULL,
	[isc_opening_date] [datetime2](0) NULL,
	[isc_closing_date] [datetime2](0) NULL,
	[isc_eligibility_criteria] [nvarchar](max) NULL,
	[isc_accredited] [bit] NULL,
	[isc_organisation_id] [int] NULL,
	[isc_contact_id] [int] NULL,
	[isc_reporting_category] [nvarchar](max) NULL,
	[isc_added_date] [datetime2](0) NULL,
	[isc_added_by_user_id] [int] NULL,
	[isc_last_updated_date] [datetime2](0) NULL,
	[isc_esh_task_id] [int] NULL,
	[isc_esh_programme_id] [int] NULL,
	[isc_approval_status] [nvarchar](max) NULL,
	[isc_approval_requested_by_user_id] [int] NULL,
	[isc_approval_requested_date] [datetime2](0) NULL,
	[isc_approval_confirmed_by_user_id] [int] NULL,
	[isc_approval_confirmed_date] [datetime2](0) NULL,
	[isc_related_isc_id] [int] NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_Intervention_Service/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO