CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_GroupSession]
(
	[group_session_id] [int] NULL,
	[grs_type] [nvarchar](max) NULL,
	[grs_title] [nvarchar](max) NULL,
	[grs_category_1] [nvarchar](max) NULL,
	[grs_category_2] [nvarchar](max) NULL,
	[grs_category_other] [nvarchar](max) NULL,
	[grs_status] [nvarchar](max) NULL,
	[grs_start_date] [nvarchar](max) NULL,
	[grs_end_date] [nvarchar](max) NULL,
	[grs_reg_type] [nvarchar](max) NULL,
	[grs_reg_open] [nvarchar](max) NULL,
	[grs_deadline_date_display] [nvarchar](max) NULL,
	[grs_deadline_time] [nvarchar](max) NULL,
	[grs_portal_reg_open] [nvarchar](max) NULL,
	[grs_max_registrations] [int] NULL,
	[grs_review_date] [nvarchar](max) NULL,
	[grs_description] [nvarchar](max) NULL,
	[grs_details_and_objectives] [nvarchar](max) NULL,
	[grs_evidence_completion] [nvarchar](max) NULL,
	[grs_delivery_method] [nvarchar](max) NULL,
	[grs_location] [nvarchar](max) NULL,
	[grs_organised_1_display] [nvarchar](max) NULL,
	[grs_organised_2_display] [nvarchar](max) NULL,
	[grs_organiser_type_display] [nvarchar](max) NULL,
	[grs_organiser_user_id] [int] NULL,
	[grs_organiser_other] [nvarchar](max) NULL,
	[grs_specialist_org_name] [nvarchar](max) NULL,
	[grs_delivered_by_display] [nvarchar](max) NULL,
	[grs_deliverer_1_display] [nvarchar](max) NULL,
	[grs_deliverer_2_display] [nvarchar](max) NULL,
	[grs_deliverer_type_display] [nvarchar](max) NULL,
	[grs_deliverer_user_fullname] [nvarchar](max) NULL,
	[grs_deliverer_other] [nvarchar](max) NULL,
	[grs_deliverer_specialist_org_name] [nvarchar](max) NULL,
	[grs_deliverer_specialist_user_fullname] [nvarchar](max) NULL,
	[grs_org_specialist_user] [nvarchar](max) NULL,
	[grs_places_left_display] [int] NULL,
	[grs_added_by_fullname] [nvarchar](max) NULL,
	[grs_added_date] [datetime2](0) NULL,
	[grs_complete_date] [datetime2](0) NULL,
	[grs_complete_by_date] [int] NULL,
	[grs_archive] [bit] NULL,
	[grs_last_updated_date] [datetime2](0) NULL,
	[grs_project_id] [int] NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_GroupSession/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO