CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_Meeting]
(
	[meeting_id] [int] NULL,
	[meet_date_time] [datetime2](0) NULL,
	[meet_booked_duration] [int] NULL,
	[meet_type] [nvarchar](max) NULL,
	[meet_type_other] [nvarchar](max) NULL,
	[meet_sub_type] [nvarchar](max) NULL,
	[meet_advisor_user_id] [int] NULL,
	[meet_external_advisor] [nvarchar](max) NULL,
	[meet_location] [nvarchar](max) NULL,
	[meet_notes] [nvarchar](max) NULL,
	[meet_dont_send_reminder] [bit] NULL,
	[meet_status] [nvarchar](max) NULL,
	[meet_duration] [int] NULL,
	[meet_related_entity_type] [nvarchar](max) NULL,
	[meet_agency_id] [int] NULL,
	[meet_site_id] [int] NULL,
	[meet_engagement_id] [int] NULL,
	[meet_organisation_id] [int] NULL,
	[meet_organisation_contact_id] [int] NULL,
	[meet_added_date] [datetime2](0) NULL,
	[meet_added_by_user_id] [int] NULL,
	[meet_complete_date] [datetime2](0) NULL,
	[meet_complete_by_user_id] [int] NULL,
	[meet_mandated] [nvarchar](max) NULL,
	[meet_action_plan_complete] [nvarchar](max) NULL,
	[meet_attendance_reason] [nvarchar](max) NULL,
	[meet_attendance_reason_other] [nvarchar](max) NULL,
	[meet_last_updated_date] [datetime2](0) NULL,
	[meet_rebooked] [nvarchar](max) NULL,
	[meet_netcall_status] [nvarchar](max) NULL,
	[meet_netcall_external_id] [nvarchar](max) NULL,
	[meet_outcome_notes] [nvarchar](max) NULL,
	[meet_ap_reviewed] [nvarchar](max) NULL,
	[meet_ap_signed_participant] [nvarchar](max) NULL,
	[meet_ap_signed_advisor] [nvarchar](max) NULL,
	[meet_ap_uploaded] [nvarchar](max) NULL,
	[meet_ap_has_interventions] [nvarchar](max) NULL,
	[meet_ap_induction_uploaded] [nvarchar](max) NULL,
	[meet_ap_status] [nvarchar](max) NULL,
	[meet_book_new_meeting] [nvarchar](max) NULL,
	[meet_not_book_new_meeting_reason] [nvarchar](max) NULL,
	[meet_future_meeting_id] [int] NULL,
	[meet_linked_ap_id] [int] NULL,
	[meet_star_diagnostic_no_reschedule_reason] [nvarchar](max) NULL,
	[meet_future_four_month_star_diagnostic_reassessment] [int] NULL,
	[meet_work_star_assessment_completed] [nvarchar](max) NULL,
	[meet_work_start_assessment_id] [int] NULL,
	[meet_ap_signature_method] [nvarchar](max) NULL,
	[meet_id_checked] [nvarchar](max) NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_Meeting/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO