CREATE EXTERNAL TABLE [DELTA].[ICONI_vBICommon_Individual]
(
	[individual_id] [INT] NULL,
	[ind_title] [NVARCHAR](MAX) NULL,
	[ind_gender] [NVARCHAR](MAX) NULL,
	[ind_forename] [NVARCHAR](MAX) NULL,
	[ind_surname] [NVARCHAR](MAX) NULL,
	[ind_known_as] [NVARCHAR](MAX) NULL,
	[ind_address1] [NVARCHAR](MAX) NULL,
	[ind_address2] [NVARCHAR](MAX) NULL,
	[ind_address3] [NVARCHAR](MAX) NULL,
	[ind_county] [NVARCHAR](MAX) NULL,
	[ind_town] [NVARCHAR](MAX) NULL,
	[ind_postcode] [NVARCHAR](MAX) NULL,
	[ind_telephone] [NVARCHAR](MAX) NULL,
	[ind_mobile] [NVARCHAR](MAX) NULL,
	[ind_email] [NVARCHAR](MAX) NULL,
	[ind_dob] [DATETIME2](0) NULL,
	[ind_age_when_added] [INT] NULL,
	[ind_natins] [NVARCHAR](MAX) NULL,
	[ind_eligibility_status] [NVARCHAR](MAX) NULL,
	[ind_eligibility_notes] [NVARCHAR](MAX) NULL,
	[ind_ethnic_origin] [NVARCHAR](MAX) NULL,
	[ind_ethnic_origin_other] [NVARCHAR](MAX) NULL,
	[ind_sms_opt_out] [BIT] NULL,
	[ind_email_opt_out] [BIT] NULL,
	[ind_valid_sms] [BIT] NULL,
	[ind_leave_message] [BIT] NULL,
	[ind_next_of_kin] [NVARCHAR](MAX) NULL,
	[ind_reasonable_adjustments] [NVARCHAR](MAX) NULL,
	[ind_safeguarding_concerns] [NVARCHAR](MAX) NULL,
	[ind_notes] [NVARCHAR](MAX) NULL,
	[ind_preferred_contact] [NVARCHAR](MAX) NULL,
	[ind_religion] [NVARCHAR](MAX) NULL,
	[ind_added_date] [DATETIME2](0) NULL,
	[ind_added_by_user_id] [INT] NULL,
	[ind_last_updated_date] [DATETIME2](0) NULL,
	[ind_translator_required] [NVARCHAR](MAX) NULL,
	[ind_translator_language] [NVARCHAR](MAX) NULL,
	[ind_translator_language_other] [NVARCHAR](MAX) NULL,
	[ind_translator_dialect] [NVARCHAR](MAX) NULL,
	[ind_restricted_by_user_id] [INT] NULL,
	[ind_restricted_date] [DATETIME2](0) NULL,
	[ind_restriction_type] [NVARCHAR](MAX) NULL,
	[ind_restriction_type_other] [NVARCHAR](MAX) NULL,
	[ind_gender_other] [NVARCHAR](MAX) NULL,
	[ValidFrom] [DATETIME2](0) NULL,
	[ValidTo] [DATETIME2](0) NULL,
	[row_sha2] [NVARCHAR](MAX) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBICommon_Individual/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO