CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_Vacancy]
(
	[vacancy_id] [int] NULL,
	[vac_organisation_id] [int] NULL,
	[vac_type] [nvarchar](max) NULL,
	[vac_theme] [nvarchar](max) NULL,
	[vac_job_title] [nvarchar](max) NULL,
	[vac_contract_type] [nvarchar](max) NULL,
	[vac_employment_type] [nvarchar](max) NULL,
	[vac_hrs_per_week] [nvarchar](max) NULL,
	[vac_salary_from] [decimal](19, 4) NULL,
	[vac_salary_to] [decimal](19, 4) NULL,
	[vac_salary_unit] [nvarchar](max) NULL,
	[vac_duration] [nvarchar](max) NULL,
	[vac_no_oppor] [int] NULL,
	[vac_working_pattern] [nvarchar](max) NULL,
	[vac_location] [nvarchar](max) NULL,
	[vac_status] [nvarchar](max) NULL,
	[vac_closing_date] [nvarchar](max) NULL,
	[vac_priority] [nvarchar](max) NULL,
	[vac_pre_screening_required] [bit] NULL,
	[vac_job_description] [nvarchar](max) NULL,
	[vac_person_specification] [nvarchar](max) NULL,
	[vac_skills_required] [nvarchar](max) NULL,
	[vac_application_process] [nvarchar](max) NULL,
	[vac_contact_details] [nvarchar](max) NULL,
	[vac_project_id] [int] NULL,
	[vac_notes] [nvarchar](max) NULL,
	[vac_version_no] [int] NULL,
	[vac_added_by_user_id] [int] NULL,
	[vac_added_date] [datetime2](0) NULL,
	[vac_complete_by_user_id] [int] NULL,
	[vac_complete_date] [nvarchar](max) NULL,
	[vac_job_broker_managed] [nvarchar](max) NULL,
	[vac_account_manager_user_id] [int] NULL,
	[vac_published_by_user_id] [int] NULL,
	[vac_published_date] [nvarchar](max) NULL,
	[vac_contact_id] [int] NULL,
	[vac_paid_by] [nvarchar](max) NULL,
	[vac_last_updated_date] [datetime2](0) NULL,
	[vac_days_per_week] [nvarchar](max) NULL,
	[vac_sent_to_textkernel] [bit] NULL,
	[vac_amt] [nvarchar](max) NULL,
	[vac_cpn] [nvarchar](max) NULL,
	[vac_cpn_organisation_id] [int] NULL,
	[vac_added_by_source] [nvarchar](max) NULL,
	[vac_added_by_external_id] [nvarchar](max) NULL,
	[vac_added_by_external_full_name] [nvarchar](max) NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_Vacancy/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO