CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_Intervention]
(
	[intervention_id] [int] NULL,
	[int_support_required] [int] NULL,
	[int_activity_type] [nvarchar](max) NULL,
	[int_advisor_user_id] [int] NULL,
	[int_owner] [nvarchar](max) NULL,
	[int_status] [nvarchar](max) NULL,
	[int_start_date] [date] NULL,
	[int_date_agreed] [date] NULL,
	[int_to_be_completed_by_date] [date] NULL,
	[int_personalised_action] [nvarchar](max) NULL,
	[int_details_and_objectives] [nvarchar](max) NULL,
	[int_evidence_completion] [nvarchar](max) NULL,
	[int_left_early_withdrawn_reason] [nvarchar](max) NULL,
	[int_end_date] [date] NULL,
	[int_total_duration] [int] NULL,
	[int_intervention_service_id] [int] NULL,
	[int_specialist_location_site_id] [int] NULL,
	[int_specialist_user_id] [int] NULL,
	[int_specialist_referral_form] [int] NULL,
	[int_specialist_status] [nvarchar](max) NULL,
	[int_specialist_complete_date] [date] NULL,
	[int_specialist_method_of_contact] [nvarchar](max) NULL,
	[int_specialist_notes] [nvarchar](max) NULL,
	[int_agency_id] [int] NULL,
	[int_site_id] [int] NULL,
	[int_engagement_id] [int] NULL,
	[int_associated_organisation_id] [int] NULL,
	[int_associated_organisation_contact_id] [int] NULL,
	[int_added_date] [datetime2](0) NULL,
	[int_added_by_user_id] [int] NULL,
	[int_complete_date] [datetime2](0) NULL,
	[int_complete_by_user_id] [int] NULL,
	[int_last_updated_date] [datetime2](0) NULL,
	[int_reviewed_actions] [nvarchar](max) NULL,
	[int_approval_status] [nvarchar](max) NULL,
	[int_rejected_reason] [nvarchar](max) NULL,
	[int_approval_by_user_id] [int] NULL,
	[int_approval_date] [datetime2](0) NULL,
	[int_outcome_notes] [nvarchar](max) NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_Intervention/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO