CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_ComplianceCSSM]
(
	[compliance_cssm_id] [int] NULL,
	[cssm_com_entity_id] [int] NULL,
	[cssm_com_entity_type] [nvarchar](max) NULL,
	[cssm_com_individual_id] [int] NULL,
	[cssm_com_type] [nvarchar](max) NULL,
	[cssm_com_score] [nvarchar](max) NULL,
	[cssm_com_advisor_user_id] [int] NULL,
	[cssm_com_site_id] [int] NULL,
	[cssm_com_date] [datetime2](0) NULL,
	[cssm_com_notes] [nvarchar](max) NULL,
	[cssm_com_failed_acknowledge] [datetime2](0) NULL,
	[cssm_com_subtype] [nvarchar](max) NULL,
	[cssm_com_recheck] [nvarchar](max) NULL,
	[cssm_previous_file_check] [nvarchar](max) NULL,
	[cssm_com_added_by_user_id] [int] NULL,
	[cssm_com_added_date] [datetime2](0) NULL,
	[cssm_com_last_updated] [datetime2](0) NULL,
	[cssm_com_complete_date] [datetime2](0) NULL,
	[cssm_com_complete_by_user_id] [int] NULL,
	[cssm_initial_meeting_30_days_referral] [nvarchar](max) NULL,
	[cssm_initial_meeting_30_days_referral_Followup] [nvarchar](max) NULL,
	[cssm_initial_meeting_30_days_referral_comments] [nvarchar](max) NULL,
	[cssm_diag_assessment_complete_within_eight_weeks] [nvarchar](max) NULL,
	[cssm_diag_assessment_complete_within_eight_weeks_Followup] [nvarchar](max) NULL,
	[cssm_diag_assessment_complete_within_eight_weeks_comments] [nvarchar](max) NULL,
	[cssm_smart_plan_in_place_eight_weeks] [nvarchar](max) NULL,
	[cssm_smart_plan_in_place_eight_weeks_Followup] [nvarchar](max) NULL,
	[cssm_smart_plan_in_place_eight_weeks_comments] [nvarchar](max) NULL,
	[cssm_received_one_to_one_support_fortnightly] [nvarchar](max) NULL,
	[cssm_received_one_to_one_support_fortnightly_Followup] [nvarchar](max) NULL,
	[cssm_received_one_to_one_support_fortnightly_comments] [nvarchar](max) NULL,
	[cssm_meeting_employment_advisor_every_four_weeks] [nvarchar](max) NULL,
	[cssm_meeting_employment_advisor_every_four_weeks_Followup] [nvarchar](max) NULL,
	[cssm_meeting_employment_advisor_every_four_weeks_comments] [nvarchar](max) NULL,
	[cssm_participant_on_scheme_no_job_outcome] [nvarchar](max) NULL,
	[cssm_participant_on_scheme_no_job_outcome_Followup] [nvarchar](max) NULL,
	[cssm_participant_on_scheme_no_job_outcome_comments] [nvarchar](max) NULL,
	[cssm_participant_diagnostic_assessment_reassessed] [nvarchar](max) NULL,
	[cssm_participant_diagnostic_assessment_reassessed_Followup] [nvarchar](max) NULL,
	[cssm_participant_diagnostic_assessment_reassessed_comments] [nvarchar](max) NULL,
	[cssm_participant_smart_action_plan_updated] [nvarchar](max) NULL,
	[cssm_participant_smart_action_plan_updated_Followup] [nvarchar](max) NULL,
	[cssm_participant_smart_action_plan_updated_comments] [nvarchar](max) NULL,
	[cssm_participant_year_without_outcome_final_action_completed] [nvarchar](max) NULL,
	[cssm_participant_year_without_outcome_final_action_completed_Followup] [nvarchar](max) NULL,
	[cssm_participant_year_without_outcome_final_action_completed_comments] [nvarchar](max) NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_ComplianceCSSM/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO