CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRefugee_Meeting_History]
(
	[meeting_id] [INT] NULL,
	[meet_date_time] [DATETIME2](0) NULL,
	[meet_booked_duration] [INT] NULL,
	[meet_type] [NVARCHAR](MAX) NULL,
	[meet_type_other] [NVARCHAR](MAX) NULL,
	[meet_sub_type] [NVARCHAR](MAX) NULL,
	[meet_advisor_user_id] [INT] NULL,
	[meet_external_advisor] [NVARCHAR](MAX) NULL,
	[meet_location] [NVARCHAR](MAX) NULL,
	[meet_notes] [NVARCHAR](MAX) NULL,
	[meet_dont_send_reminder] [BIT] NULL,
	[meet_status] [NVARCHAR](MAX) NULL,
	[meet_duration] [INT] NULL,
	[meet_related_entity_type] [NVARCHAR](MAX) NULL,
	[meet_agency_id] [INT] NULL,
	[meet_site_id] [INT] NULL,
	[meet_engagement_id] [INT] NULL,
	[meet_organisation_id] [INT] NULL,
	[meet_organisation_contact_id] [INT] NULL,
	[meet_added_date] [DATETIME2](0) NULL,
	[meet_added_by_user_id] [INT] NULL,
	[meet_complete_date] [DATETIME2](0) NULL,
	[meet_complete_by_user_id] [INT] NULL,
	[meet_mandated] [NVARCHAR](MAX) NULL,
	[meet_action_plan_complete] [NVARCHAR](MAX) NULL,
	[meet_attendance_reason] [NVARCHAR](MAX) NULL,
	[meet_attendance_reason_other] [NVARCHAR](MAX) NULL,
	[meet_last_updated_date] [DATETIME2](0) NULL,
	[meet_rebooked] [NVARCHAR](MAX) NULL,
	[meet_netcall_status] [NVARCHAR](MAX) NULL,
	[meet_netcall_external_id] [NVARCHAR](MAX) NULL,
	[meet_outcome_notes] [NVARCHAR](MAX) NULL,
	[meet_ap_reviewed] [NVARCHAR](MAX) NULL,
	[meet_ap_signed_participant] [NVARCHAR](MAX) NULL,
	[meet_ap_signed_advisor] [NVARCHAR](MAX) NULL,
	[meet_ap_uploaded] [NVARCHAR](MAX) NULL,
	[meet_ap_has_interventions] [NVARCHAR](MAX) NULL,
	[meet_ap_induction_uploaded] [NVARCHAR](MAX) NULL,
	[meet_ap_status] [NVARCHAR](MAX) NULL,
	[meet_book_new_meeting] [NVARCHAR](MAX) NULL,
	[meet_not_book_new_meeting_reason] [NVARCHAR](MAX) NULL,
	[meet_future_meeting_id] [INT] NULL,
	[meet_linked_ap_id] [INT] NULL,
	[meet_star_diagnostic_no_reschedule_reason] [NVARCHAR](MAX) NULL,
	[meet_future_four_month_star_diagnostic_reassessment] [INT] NULL,
	[meet_work_star_assessment_completed] [NVARCHAR](MAX) NULL,
	[meet_work_start_assessment_id] [INT] NULL,
	[meet_ap_signature_method] [NVARCHAR](MAX) NULL,
	[meet_id_checked] [NVARCHAR](MAX) NULL,
	[ValidFrom] [DATETIME2](0) NULL,
	[ValidTo] [DATETIME2](0) NULL,
	[row_sha2] [NVARCHAR](MAX) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRefugee_Meeting/IsCurrent=false',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO


