CREATE EXTERNAL TABLE [DELTA].[ICONI_vBIRestart_Outcome]
(
	[outcome_id] [int] NULL,
	[out_type] [nvarchar](max) NULL,
	[out_type_other] [nvarchar](max) NULL,
	[out_date] [datetime2](0) NULL,
	[out_advisor_user_id] [int] NULL,
	[out_notes] [nvarchar](max) NULL,
	[out_status] [nvarchar](max) NULL,
	[out_follow_up_date] [datetime2](0) NULL,
	[out_eng_start_date] [datetime2](0) NULL,
	[out_reason_for_leaving] [nvarchar](max) NULL,
	[out_reason_for_leaving_other] [nvarchar](max) NULL,
	[out_job_title] [nvarchar](max) NULL,
	[out_job_type] [nvarchar](max) NULL,
	[out_contract_type] [nvarchar](max) NULL,
	[out_employee_identifier] [nvarchar](max) NULL,
	[out_salary_amount] [decimal](19, 4) NULL,
	[out_salary_unit] [nvarchar](max) NULL,
	[out_hrs_per_week] [decimal](19, 2) NULL,
	[out_duration] [nvarchar](max) NULL,
	[out_job_source] [nvarchar](max) NULL,
	[out_job_source_other] [nvarchar](max) NULL,
	[out_wage_category] [nvarchar](max) NULL,
	[out_paid_by] [nvarchar](max) NULL,
	[out_organisation] [nvarchar](max) NULL,
	[out_progression_type] [nvarchar](max) NULL,
	[out_left_date] [datetime2](0) NULL,
	[out_prap_upload_date] [date] NULL,
	[out_provider_agency_id] [int] NULL,
	[out_site_id] [int] NULL,
	[out_engagement_id] [int] NULL,
	[out_employer_organisation_id] [int] NULL,
	[out_employer_contact_id] [int] NULL,
	[out_added_date] [datetime2](0) NULL,
	[out_added_by_user_id] [int] NULL,
	[out_complete_date] [datetime2](0) NULL,
	[out_complete_by_user_id] [int] NULL,
	[out_salary_actual_date] [nvarchar](max) NULL,
	[out_hoursweek_actual_date] [nvarchar](max) NULL,
	[out_unit_actual_date] [nvarchar](max) NULL,
	[out_vacancy_id] [int] NULL,
	[out_vacancy_interest_id] [int] NULL,
	[out_last_uppdated_date] [datetime2](0) NULL,
	[out_verification_date] [datetime2](0) NULL,
	[out_verification_status] [nvarchar](max) NULL,
	[out_verification_status_details] [nvarchar](max) NULL,
	[out_sub_type] [nvarchar](max) NULL,
	[out_did_not_start_reason] [nvarchar](max) NULL,
	[out_did_not_start_reason_other] [nvarchar](max) NULL,
	[out_days_per_wk] [nvarchar](max) NULL,
	[out_cpn] [nvarchar](max) NULL,
	[out_cpn_organisation_id] [int] NULL,
	[ValidFrom] [datetime2](0) NULL,
	[ValidTo] [datetime2](0) NULL,
	[row_sha2] [nvarchar](max) NULL
)
WITH (DATA_SOURCE = [ADLG2_PSA],LOCATION = N'delta/ICONI/vBIRestart_Outcome/IsCurrent=true',FILE_FORMAT = [parquet_file_format],REJECT_TYPE = VALUE,REJECT_VALUE = 0)
GO