CREATE VIEW [DV].[Base_DeliverySite_Iconi] AS SELECT
CONVERT(CHAR(66),H.DeliverySiteHash ,1) AS DeliverySiteHash
,H.RecordSource
,S_IC.DeliverySiteName
,CAST(NULL AS NVARCHAR(MAX)) AS Status
,CAST(NULL AS NVARCHAR(255)) AS Zone
,CAST(NULL AS NVARCHAR(255)) AS ReportingRegion
,CAST(NULL AS NVARCHAR(255)) AS ReportingAreaBranch
,CAST(NULL AS NVARCHAR(255)) AS ReportingZone
,NULL AS BaanRegion
,NULL AS BaanAreaBranch
,CAST(NULL AS VARCHAR(10)) AS BaanZone
,NULL AS DSRegion
,NULL AS TempID
,CAST(NULL AS VARCHAR(50)) AS Ofsted
,CAST(NULL AS VARCHAR(255)) AS ROM
,CAST(NULL AS VARCHAR(255)) AS Delivery
,CAST(NULL AS VARCHAR(255)) AS BranchManager
,CAST(NULL AS VARCHAR(2000)) AS BranchManagerEmail
,CAST(NULL AS VARCHAR(2000)) AS ROMEmail
,CAST(NULL AS VARCHAR(255)) AS WPSite
,CAST(NULL AS VARCHAR(2000)) AS EmailCC
,CAST(NULL AS VARCHAR(50)) AS CPA
,CAST(NULL AS VARCHAR(255)) AS NorthSouth
,CAST(NULL AS VARCHAR(255)) AS QualityManager
,NULL AS IsActive
,CAST(NULL AS VARCHAR(255)) AS ReportingHierarchy
,CAST(NULL AS VARCHAR(255)) AS RegionSES
,CAST(NULL AS VARCHAR(255)) AS BranchOwner
,CAST(NULL AS VARCHAR(255)) AS FinanceName
,CAST(NULL AS VARCHAR(8)) AS BranchManagerEmpNo
,CAST(NULL AS VARCHAR(255)) AS WHPLot
,CAST(NULL AS VARCHAR(255)) AS DataOwner
,0 AS DDA
FROM 
DV.HUB_DeliverySite H
LEFT JOIN DV.SAT_DeliverySite_Iconi_Core S_IC ON H.DeliverySiteHash = S_IC.DeliverySiteHash
WHERE H.RecordSource = 'ICONI.Engagement';
GO
