CREATE VIEW [DV].[Base_Assignment_Default] AS SELECT
CONVERT(CHAR(66),CAST(0x0 AS BINARY(32)) ,1)	AS AssignmentHash,
CAST('Unknown' AS VARCHAR(50))					AS RecordSource,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentID,
CAST('Unknown' AS NVARCHAR(MAX))				AS JobTitle,
CAST('Unknown' AS NVARCHAR(MAX))				AS ContractType,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentType,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentStatus,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentLeaveReason,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentIndustry,
CAST('Unknown' AS NVARCHAR(MAX))				AS WorkRelatedActivityType,
CAST(0 AS DECIMAL(5,2))							AS ContractedHours,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentStartClaimYear,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentOutcomeTwoClaimYear,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentOutcomeOneClaimYear,
CAST('Unknown' AS NVARCHAR(MAX))				AS SelfEmployed,
CAST('Unknown' AS NVARCHAR(MAX))				AS DiscountMilestone,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentOwningEmployee,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentStartPaymentCycle,
CAST('Unknown' AS NVARCHAR(MAX))				AS AssignmentStartSelfEmployedVerified,
CAST('Unknown' AS NVARCHAR(MAX))				AS WageCategory,
CAST(0 AS DECIMAL(6,2))							AS WeeklyHours,
CAST('Unknown' AS NVARCHAR(MAX))				AS WageException,
CAST('Unknown' AS NVARCHAR(MAX))				AS TempPerm;
GO

