CREATE VIEW [DV].[Base_Vacancy_Iconi] AS SELECT
	CONVERT(CHAR(66),V.VacancyHash,1)						AS VacancyHash,
	V.RecordSource											AS RecordSource,
	REPLACE(S_VC.VacancyKey,'ICONI|','')					AS VacancyReferenceKey,
	S_VC.VacancyStatus										AS VacancyStatus,
	S_VC.VacancyJobTitle									AS VacancyJobTitle,
	S_VC.VacancyJobDescription								AS VacancyDuties,
	S_VC.VacancyNotes										AS VacancyDetails,
	S_VC.VacancyPersonSpec									AS VacancyPersonSpec,
	S_VC.VacancyApplicationDetails							AS VacancyApplicationDetails,
	CAST(NULL AS NVARCHAR(MAX))								AS ReasonForVacancy,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyDepartment,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyIsExclusive,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyReportsTo,
	S_VC.VacancyContractType								AS VacancyContractType,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyCRBCheckRequired,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyPayFrequency,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyWeekendWorkRequired,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyNightWorkRequired,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyShiftWorkRequired,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancySOCCode,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyApplicationMethod,
	CAST(NULL AS NVARCHAR(MAX))								AS JobOppotunityCategory,
	CAST(S_VC.VacancyContractedWeeklyHours AS DECIMAL(5,2))	AS ContractedWeeklyHours,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyEmployerReference,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancySource,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyPositionsRemaining,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyDrivingLicenceRequired,			
	CAST(NULL AS INT)										AS VacancyOriginalNumberRequired,
	CAST(NULL AS INT)										AS VacancySalaryCurrency,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyInvoicePoint,
	S_VC.VacancyWorkingPattern								AS VacancyWorkingHours,
	NULL													AS VacancyMinimumEducationLevel,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyPaymentInterval,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyPermanence,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyWageCategory,
	S_VC.VacancySkillsRequired								AS VacancySkillsRequired,
	S_VC.VacancyLocationDetails								AS VacancyLocationDetails,
	CAST(S_VC.VacancyProjectID AS NVARCHAR(MAX))			AS VacancyProjectID,
	CAST(S_VC.VacancyVersionNo AS NVARCHAR(MAX))			AS VacancyVersionNo,
	S_VC.VacancyJobBrokerManaged							AS VacancyJobBrokerManaged,
	CAST(S_VC.VacancyContact AS NVARCHAR(MAX))				AS VacancyContact,
	CAST(NULL AS NVARCHAR(MAX))								AS VacancyAddUser
FROM
	DV.HUB_Vacancy V
	LEFT JOIN DV.SAT_Vacancy_Iconi_Core AS S_VC
	ON V.VacancyKey = S_VC.VacancyKey AND S_VC.IsCurrent = 1
WHERE V.RecordSource = 'ICONI.Vacancy';
GO
