CREATE VIEW [DV].[Base_Date]
AS SELECT * FROM (
SELECT [Date_Skey] AS Date_Key
      ,[Date] 
      ,[Full_Date]
      ,[Date_Description]
      ,[Full_Date_Description]
      ,[Day_Of_Month]
      ,[Day_Of_Month_Suffix]
      ,[Day_Name_Short]
      ,[Day_Name_Long]
      ,[Week_Code]
      ,[Week_Number]
      ,[Week_Number_Full]
      ,[Month_Code]
      ,[Month_Name_Short]
      ,[Month_Name_Long]
      ,[Month_Number]
      ,[Month_Number_Full]
      ,[Quarter_Code]
      ,[Quarter_Number]
      ,[Quarter_Short_Name]
      ,[Quarter_Long_Name]
      ,[Semester_Code]
      ,[Semester_Number]
      ,[Semester_Short_Name]
      ,[Semester_Long_Name]
      ,[Year_Code]
      ,[Year_Number]
      ,[Year_Name]
      ,[Report_Period]
      ,[Rolling_Week]
      ,[Day_Reverse_Count_Key]
      ,[Day_Count_Key]
      ,[Fiscal_Year]
      ,[Fiscal_Year_Name]
      ,[Fiscal_Semester_Number]
      ,[Fiscal_Semester_Short_Name]
      ,[Fiscal_Semester_Long_Name]
      ,[Fiscal_Quarter_Number]
      ,[Fiscal_Quarter_Short_Name]
      ,[Fiscal_Quarter_Full_Name]
      ,[Fiscal_Month_Number]
      ,[Fiscal_Month_Full_Name]
      ,[Is_Calendar_Month_End]
      ,[Is_Accounting_Month_End]
      ,[Is_Calendar_Quarter_End]
      ,[Is_Calendar_Year_End]
      ,[Is_Accounting_Year_End]
      ,[Is_Business_Day]
      ,[Is_Holiday]
      ,[Is_Weekend]
      ,[Savings_Week]
      ,[Active_Performance_Period]
      ,[End_Of_Week_Date]
      ,[Month_Year_Name]
      ,[Day_Of_Month_Reversed]
      ,[CHDA_Contract_Year_Code]
      ,[CHDA_Contract_Year_Number]
      ,[CHDA_Contract_Year_Name]
      ,[CHDA_Contract_Month_Code]
      ,[CHDA_Contract_Month_Number_Full]
      ,[CHDA_Contract_Month_Number]
      ,[Year_Month_Number]
      ,[Year_Quarter_Number]
      ,[CHDA_Contract_Year_Month_Number]
      ,[CHDA_Contract_Year_Quarter_Number]
      ,[Previous_Year_Month_Number]
      ,[Business_Day_Of_Month]
      ,[Business_Day_Of_Month_Reversed]
      ,[Business_Days_In_Month]
      ,[End_Of_Week_Date_Sunday]
      ,[Non_Business_Days_In_Month]
      ,[Is_Business_Day_Scotland]
      ,[Is_Holiday_Scotland]
      ,[Business_Day_Of_Month_Scotland]
      ,[Business_Day_Of_Month_Reversed_Scotland]
      ,[Business_Days_In_Month_Scotland]
      ,[Non_Business_Days_In_Month_Scotland]
      ,[Holiday_Year]
      ,[Fiscal_Week_Number]
      ,[Calendar_Reporting_Month_Name]
      ,[Calendar_Reporting_Week_Number]
      ,[Fiscal_Week_Number_In_Month]
      ,[Fiscal_Month_Name]
      ,[This Year YTD]
      ,[Last Year YTD]
      ,[Current Month MTD]
      ,[Last Full Month]
      ,[Last Full Year]
      ,[Working Days Index Field]
      ,[Last Full Week]
      ,[Last Full Quarter]
      ,[Last Full Financial Year Quarter]
      ,[Financial Year Month Number]
      ,[DayIndex]
      ,[MonthIndex]
      ,[YearIndex]
      ,[Created_Date]
      ,[Modified_Date]
      ,[Created_By]
      ,[Modified_By], ROW_NUMBER() OVER (PARTITION BY [DATE]  ORDER BY Date) AS DateRank
  FROM [DW].[D_Date]
  ) D WHERE D.DateRank = 1;