CREATE VIEW [DV].[Dimension_Employee]
AS SELECT
 [EmployeeHash]
,[RecordSource]
,[EmployeeName]
,[EmployeeFirstName]
,[EmployeeLastName]
,[EmployeeAgency]
,[EmployeeEmail]
,[EmployeeSuspendedDate]
,[EmployeeType]
,[EmployeeOrganisation]
,[EmployeeAddedDate]
,[EmployeeUsername]
,[EmployeeSupportsOver50]
,[EmployeeLocked]
,[EmployeeSsoIdentifier]
,[EmployeeSsoEnabled]
,[EmployeeJobTitle]
,[EmployeeNotes]
,[EmployeeLastLogin]
,[EmployeeArchive]
,[EmployeeTimeoutTimer]
,[EmployeeLicencingProg]
,[EmployeeLastUpdatedDate]
,[Team]

FROM (
		SELECT
			 [EmployeeHash]
			,row_number() OVER (PARTITION BY [EmployeeHash] ORDER BY [EmployeeHash]) rn
			,[RecordSource]
			,[EmployeeName]
			,[EmployeeFirstName]
			,[EmployeeLastName]
			,[EmployeeAgency]
			,[EmployeeEmail]
			,[EmployeeSuspendedDate]
			,[EmployeeType]
			,[EmployeeOrganisation]
			,[EmployeeAddedDate]
			,[EmployeeUsername]
			,[EmployeeSupportsOver50]
			,[EmployeeLocked]
			,[EmployeeSsoIdentifier]
			,[EmployeeSsoEnabled]
			,[EmployeeJobTitle]
			,[EmployeeNotes]
			,[EmployeeLastLogin]
			,[EmployeeArchive]
			,[EmployeeTimeoutTimer]
			,[EmployeeLicencingProg]
			,[EmployeeLastUpdatedDate]
			,[Team]

			FROM [DV].[Base_Employee]
		) src
WHERE (rn = 1);
GO

