CREATE VIEW [DV].[Dimension_Assignment] AS SELECT

[AssignmentHash]
,[RecordSource]
,[AssignmentID]
,[JobTitle]
,[ContractType]
,[AssignmentType]
,[AssignmentStatus]
,[AssignmentLeaveReason]
,[AssignmentIndustry]
,[WorkRelatedActivityType]
,[ContractedHours]
,[AssignmentStartClaimYear]
,[AssignmentOutcomeTwoClaimYear]
,[AssignmentOutcomeOneClaimYear]
,[SelfEmployed]
,[DiscountMilestone]
,[AssignmentOwningEmployee]
,[AssignmentStartPaymentCycle]
,[AssignmentStartSelfEmployedVerified]
,[WageCategory]
,[WeeklyHours]
,[WageException]
,[TempPerm]
FROM (
		SELECT 
				 [AssignmentHash]
				,row_number() OVER (PARTITION BY [AssignmentHash] ORDER BY [AssignmentHash]) rn
				,[RecordSource]
				,[AssignmentID]
				,[JobTitle]
				,[ContractType]
				,[AssignmentType]
				,[AssignmentStatus]
				,[AssignmentLeaveReason]
				,[AssignmentIndustry]
				,[WorkRelatedActivityType]
				,[ContractedHours]
				,[AssignmentStartClaimYear]
				,[AssignmentOutcomeTwoClaimYear]
				,[AssignmentOutcomeOneClaimYear]
				,[SelfEmployed]
				,[DiscountMilestone]
				,[AssignmentOwningEmployee]
				,[AssignmentStartPaymentCycle]
				,[AssignmentStartSelfEmployedVerified]
				,[WageCategory]
				,[WeeklyHours]
				,[WageException]
				,[TempPerm]

				FROM [DV].[Base_Assignment]
		) src
WHERE (rn = 1);
GO

