CREATE VIEW [DV].[Dimension_Participant] AS SELECT
 [ParticipantHash]
,[RecordSource]
,[ParticipantID]
,[FullName]
,[Title]
,[FirstName]
,[MiddleName]
,[LastName]
,[KnownAs]
,[DateOfBirth]
,[NationalInsuranceNo]
,[ValidSMS]
,[SMSOptOut]
,[EmailOptOut]
,[LeaveMessage]
,[HasCriminalConviction]
,[IsDriver]
,[BetterOffCalculationStatus]
,[HasOwnTransport]
,[MarketingPermissions]
,[HasUpToDateCV]
,[AddressLine1]
,[AddressLine2]
,[Locality]
,[Town]
,[County]
,[PostCode]
,[PostCodeSector]
,[TelephoneHome]
,[TelephoneMobile]
,[TelephoneWork]
,[EmailWork]
,[EmailHome]
,[VacancyGoal1]
,[VacancyGoal2]
,[VacancyGoal3]
,[PreferredCommunicationMethod]
,[ContactStatus]
,[SexualOrientation]
,[Gender]
,[Ethnicity]

FROM (

	SELECT
	 [ParticipantHash]
	,ROW_NUMBER() OVER (PARTITION BY [ParticipantHash] ORDER BY [ParticipantHash]) rn
	,[RecordSource]
	,[ParticipantID]
	,[FullName]
	,[Title]
	,[FirstName]
	,[MiddleName]
	,[LastName]
	,[KnownAs]
	,[DateOfBirth]
	,[NationalInsuranceNo]
	,[ValidSMS]
	,[SMSOptOut]
	,[EmailOptOut]
	,[LeaveMessage]
	,[HasCriminalConviction]
	,[IsDriver]
	,[BetterOffCalculationStatus]
	,[HasOwnTransport]
	,[MarketingPermissions]
	,[HasUpToDateCV]
	,[AddressLine1]
	,[AddressLine2]
	,[Locality]
	,[Town]
	,[County]
	,[PostCode]
	,[PostCodeSector]
	,[TelephoneHome]
	,[TelephoneMobile]
	,[TelephoneWork]
	,[EmailWork]
	,[EmailHome]
	,[VacancyGoal1]
	,[VacancyGoal2]
	,[VacancyGoal3]
	,[PreferredCommunicationMethod]
	,[ContactStatus]
	,[SexualOrientation]
	,[Gender]
	,[Ethnicity]

	FROM [DV].[Base_Participant]
		) src
WHERE (rn = 1);
GO
