CREATE VIEW [DV].[Dimension_DeliverySite]
AS SELECT
[DeliverySiteHash]
,[RecordSource]
,[DeliverySiteName]
,[Status]
,[Zone]
,[ReportingRegion]
,[ReportingAreaBranch]
,[ReportingZone]
,[BaanRegion]
,[BaanAreaBranch]
,[BaanZone]
,[Capacity]
,[DSRegion]
,[TempID]
,[Ofsted]
,[ROM]
,[Delivery]
,[BranchManager]
,[BranchManagerEmail]
,[ROMEmail]
,[WPSite]
,[EmailCC]
,[CPA]
,[NorthSouth]
,[QualityManager]
,[IsActive]
,[ReportingHierarchy]
,[RegionSES]
,[BranchOwner]
,[FinanceName]
,[BranchManagerEmpNo]
,[WHPLot]
,[DataOwner]
,[DDA]
FROM (
	SELECT
		[DeliverySiteHash]
		,ROW_NUMBER() OVER (PARTITION BY [DeliverySiteHash] ORDER BY [DeliverySiteHash]) rn
		,[RecordSource]
		,[DeliverySiteName]
		,[Status]
		,[Zone]
		,[ReportingRegion]
		,[ReportingAreaBranch]
		,[ReportingZone]
		,[BaanRegion]
		,[BaanAreaBranch]
		,[BaanZone]
		,[DSRegion]
		,0 as [Capacity]
		,[TempID]
		,[Ofsted]
		,[ROM]
		,[Delivery]
		,[BranchManager]
		,[BranchManagerEmail]
		,[ROMEmail]
		,[WPSite]
		,[EmailCC]
		,[CPA]
		,[NorthSouth]
		,[QualityManager]
		,[IsActive]
		,[ReportingHierarchy]
		,[RegionSES]
		,[BranchOwner]
		,[FinanceName]
		,[BranchManagerEmpNo]
		,[WHPLot]
		,[DataOwner]
		,[DDA]
		FROM [DV].[Base_DeliverySite]
	) src
WHERE (rn = 1);
GO
