CREATE VIEW [DV].[Dimension_Vacancy] AS SELECT
 [VacancyHash]
,[RecordSource]
,[VacancyReferenceKey]
,[VacancyStatus]
,[VacancyJobTitle]
,[ReasonForVacancy]
,[VacancyDepartment]
,[VacancyIsExclusive]
,[VacancyReportsTo]
,[VacancyContractType]
,[VacancyCRBCheckRequired]
,[VacancyPayFrequency]
,[VacancyWeekendWorkRequired]
,[VacancyNightWorkRequired]
,[VacancyShiftWorkRequired]
,[VacancySOCCode]
,[VacancyApplicationMethod]
,[JobOppotunityCategory]
,[VacancyContractedWeeklyHours]
,[VacancyEmployerReference]
,[VacancySource]
,[VacancyPositionsRemaining]
,[VacancyDrivingLicenceRequired]
,[VacancyOriginalNumberRequired]
,[VacancySalaryCurrency]
,[VacancyInvoicePoint]
,[VacancyWorkingHours]
,[VacancyMinimumEducationLevel]
,[VacancyPaymentInterval]
,[VacancyPermanence]
,[VacancyWageCategory]
,[VacancyAddUser]

FROM (
		SELECT
		 [VacancyHash]
		,ROW_NUMBER() OVER (PARTITION BY [VacancyHash] ORDER BY [VacancyHash]) rn
		,[RecordSource]
		,[VacancyReferenceKey]
		,[VacancyStatus]
		,[VacancyJobTitle]
		,[ReasonForVacancy]
		,[VacancyDepartment]
		,[VacancyIsExclusive]
		,[VacancyReportsTo]
		,[VacancyContractType]
		,[VacancyCRBCheckRequired]
		,[VacancyPayFrequency]
		,[VacancyWeekendWorkRequired]
		,[VacancyNightWorkRequired]
		,[VacancyShiftWorkRequired]
		,[VacancySOCCode]
		,[VacancyApplicationMethod]
		,[JobOppotunityCategory]
		,[VacancyContractedWeeklyHours]
		,[VacancyEmployerReference]
		,[VacancySource]
		,[VacancyPositionsRemaining]
		,[VacancyDrivingLicenceRequired]
		,[VacancyOriginalNumberRequired]
		,[VacancySalaryCurrency]
		,[VacancyInvoicePoint]
		,[VacancyWorkingHours]
		,[VacancyMinimumEducationLevel]
		,[VacancyPaymentInterval]
		,[VacancyPermanence]
		,[VacancyWageCategory]
		,[VacancyAddUser]
		FROM [DV].[Base_Vacancy]
		) src
WHERE (rn = 1);
GO
