CREATE VIEW [ADAPT].[BUSINESS_OBJECTS]
AS SELECT [BO_ID], [CATEGORY_ID], [CONFIG_NAME], [SECURITY_LEVEL], [VERSION_NUMBER], [CREATED_BY], [CREATED_DATE], [UPDATED_BY], [UPDATED_DATE], [LOCKED_DOWN], [PREVIEW], [JAVA_BO], [LEGACY_CLASS], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_BUSINESS_OBJECTS;
