CREATE VIEW [ADAPT].[CODES]
AS 
SELECT [CODE_ID], [PARENT_CODE_ID], [GROUP_ID], [NAME], [LANGUAGE_ID], [GLOBAL_CODE_ID], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent 
FROM DELTA.ADAPT_CODES 
UNION ALL 
SELECT [CODE_ID], [PARENT_CODE_ID], [GROUP_ID], [NAME], [LANGUAGE_ID], [GLOBAL_CODE_ID], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent 
FROM DELTA.ADAPT_CODES_History;
