CREATE VIEW [ADAPT].[DOCUMENT_CATEGORIES]
AS SELECT [CATEGORY_ID], [PARENT_ID], [SEARCHABLE], [READ_ACCESS], [MODIFY_ACCESS], [DELETE_ACCESS], [LOCKED_DOWN], [CONFIG_NAME], [DOC_CONTENT_LIMIT_SIZE], [IS_DIRTY], [GROUP_ID], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_DOCUMENT_CATEGORIES;
