CREATE VIEW [ADAPT].[ENTITY_TABLE]
AS SELECT [ENTITY_ID], [STATUS], [CREATEDDATE], [CREATED_BY], [UPDATEDDATE], [UPDATED_BY], [DELETEDDATE], [DELETED_BY], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_ENTITY_TABLE UNION ALL SELECT [ENTITY_ID], [STATUS], [CREATEDDATE], [CREATED_BY], [UPDATEDDATE], [UPDATED_BY], [DELETEDDATE], [DELETED_BY], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_ENTITY_TABLE_History;
GO

