CREATE VIEW [ADAPT].[HUB_Entity] AS SELECT
CONCAT_WS('|','ADAPT',CAST(ET.ENTITY_ID AS INT)) AS EntityKey
,'ADAPT.ENTITY_TABLE' AS RecordSource
,ValidFrom
,ValidTo
,IsCurrent
FROM ADAPT.ENTITY_TABLE ET
WHERE ISNULL(ET.STATUS,'D') = 'D';
GO