CREATE VIEW [ADAPT].[HUB_Participant] 
AS SELECT 
	CONCAT_WS('|','ADAPT',CAST(PG.PERSON_ID AS INT)) AS ParticipantKey,
	'ADAPT.PROP_PERSON_GEN' AS RecordSource,
	PG.ValidFrom,
	PG.ValidTo,
	PG.IsCurrent
FROM ADAPT.PROP_PERSON_GEN PG
INNER JOIN ADAPT.VW_LK_ENTITY_ROLE vr ON vr.REFERENCE = PG.REFERENCE AND vr.IsCurrent = '1';