CREATE VIEW [ADAPT].[HUB_HMRC] AS (
SELECT 
CONCAT_WS('|','ADAPT',[REFERRAL NUMBER], [NOTIFICATION TYPE] ) AS HMRCKey
,'ADAPT.EXTERNAL.XL' AS RecordSource
,[ValidFrom] 	 AS ValidFrom
,'9999-12-31 23:59:59' AS ValidTo
,1 AS IsCurrent
FROM [LZ].[hmrc_Files]
WHERE
[DATE CREATED] <> 'DATE CREATED'
);
GO