CREATE VIEW [ADAPT].[HUB_DeliverySite]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(REFERENCE AS INT)) AS DeliverySiteKey,
'ADAPT.PROP_CLIENT_GEN' AS RecordSource,
CG.ValidFrom, CG.ValidTo, CG.IsCurrent
FROM ADAPT.PROP_CLIENT_GEN CG WHERE REFERENCE IN (
	SELECT DISTINCT CORE_PROVID FROM ADAPT.PROP_WP_GEN W WHERE W.IsCurrent = 1
);
