CREATE VIEW [ADAPT].[HUB_RequestingSite]
AS SELECT 
TRIM(ST_LOCATION) AS RequestingSiteKey,
'ADAPT.PROP_CAND_PRAP' AS RecordSource,
MIN(ValidFrom) ValidFrom, MAX(ValidTo) ValidTo, CAST(1 AS BIT) AS IsCurrent
FROM ADAPT.PROP_CAND_PRAP
WHERE NULLIF(ST_LOCATION,'') IS NOT NULL AND IsCurrent = 1
GROUP BY TRIM(ST_LOCATION);