CREATE VIEW [ADAPT].[JOURNAL_ENTRIES]
AS SELECT [ID], [CREATION_DATE], [CREATOR_ID], [BO_ID], [ENTITY_ID_1], [ENTITY_ID_2], [ENTITY_ID_3], [ENTITY_ID_4], [ENTITY_ID_5], [ENTITY_ID_6], [ROLE_ID_1], [ROLE_ID_2], [ROLE_ID_3], [ROLE_ID_4], [ROLE_ID_5], [ROLE_ID_6], [J_NOTES], [J_DOCUMENT], [ValidFrom], [ValidTo], CAST(1 AS BIT) AS IsCurrent FROM DELTA.adapt_JOURNAL_ENTRIES;
