CREATE VIEW [ADAPT].[LINK_Case_Barriers] AS (
SELECT 
CONCAT_WS('|','ADAPT',CAST(pb.CONTRACT AS INT)) AS CaseKey,
CONCAT_WS('|','ADAPT',CAST(bg.[REFERENCE] AS INT)) AS BarrierKey,
'ADAPT.PROP_BARRIER_GEN'						AS RecordSource,
bg.[ValidFrom], 
bg.[ValidTo], 
bg.IsCurrent 
FROM 
ADAPT.PROP_BARRIER_GEN bg
INNER JOIN ADAPT.PROP_X_PC_BARRIER pb ON pb.BARRIER = bg.REFERENCE
);
GO