CREATE VIEW [ADAPT].[LINK_Vacancy_JobCategory]
AS SELECT
	CONCAT_WS('|','ADAPT',CAST(J.JOB_ID AS INT)) AS VacancyKey,
	CONCAT_WS('|','ADAPT', CAST(C.REFERENCE AS INT)) AS JobCategoryKey,
	'ADAPT.PROP_JOB_CAT' AS RecordSource,
	C.ValidFrom, 
	C.ValidTo, 
	C.IsCurrent

FROM 
	ADAPT.PROP_JOB_CAT	AS C
	INNER JOIN
	ADAPT.PROP_JOB_GEN	AS J
	ON J.REFERENCE = C.REFERENCE;
GO