CREATE VIEW [ADAPT].[LINK_Case_DeliverySite] AS SELECT
	CONCAT_WS('|','ADAPT',CAST(W.REFERENCE AS INT)) AS CaseKey,
	CONCAT_WS('|','ADAPT',CAST(W.CORE_PROVID AS INT)) AS DeliverySiteKey,
	'ADAPT.PROP_WP_GEN' AS RecordSource,
	ValidFrom, ValidTo, IsCurrent
	FROM ADAPT.PROP_WP_GEN W
	WHERE NULLIF(CAST(CAST(W.CORE_PROVID AS INT) AS VARCHAR),'') IS NOT NULL AND NULLIF(CAST(CAST(W.REFERENCE AS INT) AS VARCHAR),'') IS NOT NULL
	and IsCurrent = 1;
GO