CREATE VIEW [ADAPT].[LINK_Document_Employee] AS SELECT
CONCAT_WS('|','ADAPT',CAST(D.ID AS INT)) AS DocumentKey,
CONCAT_WS('|','ADAPT', CAST(E.REFERENCE AS INT)) AS EmployeeKey,
'ADAPT.PROP_DOCTRACK_GEN' AS RecordSource,
D.ValidFrom, D.ValidTo, D.IsCurrent
FROM ADAPT.PROP_DOCTRACK_GEN D
LEFT OUTER JOIN ADAPT.PROP_EMPLOYEE_GEN E ON D.SENDER = E.USER_REF AND E.IsCurrent = 1
WHERE 
D.ID IS NOT NULL
AND D.IsCurrent = 1;
GO