CREATE VIEW [ADAPT].[LINK_JobCategory_Vacancy]
AS SELECT
	CONCAT_WS('|','ADAPT',CAST(J.JOB_ID AS INT)) AS VacancyKey,
	CONCAT_WS('|','ADAPT', CAST(C.REFERENCE AS INT)) AS JobCategoryKey,
	'ADAPT.PROP_JOB_CAT' AS RecordSource,
	J.ValidFrom, 
	J.ValidTo, 
	J.IsCurrent

FROM 
	ADAPT.PROP_JOB_GEN	AS J
	LEFT JOIN
	ADAPT.PROP_JOB_CAT	AS C
	ON J.REFERENCE = C.REFERENCE;
GO
