CREATE VIEW [ADAPT].[LINK_Case_Participant] AS SELECT 
CONCAT_WS('|','ADAPT',CAST(P.WIZPROG AS INT)) AS CaseKey,
CONCAT_WS('|','ADAPT',CAST(PP.PERSON_ID AS INT)) AS ParticipantKey,
'ADAPT.PROP_X_CAND_WP' AS RecordSource,
P.ValidFrom,
P.ValidTo,
P.IsCurrent
FROM ADAPT.PROP_X_CAND_WP P
	INNER JOIN ADAPT.PROP_PERSON_GEN PP ON PP.REFERENCE = P.CANDIDATE AND PP.IsCurrent = '1'
	INNER JOIN ADAPT.VW_LK_ENTITY_ROLE vr ON vr.REFERENCE = PP.REFERENCE AND vr.IsCurrent = '1'
WHERE NULLIF(CAST(P.WIZPROG AS INT),'') IS NOT NULL AND NULLIF(CAST(PP.PERSON_ID AS INT),'') IS NOT NULL;
GO