CREATE VIEW [ADAPT].[LINK_Case_Referral] AS SELECT 
CONCAT_WS('|','ADAPT',CAST(R.REFERENCE AS INT)) AS CaseKey,
CONCAT_WS('|','ADAPT',CAST(R.REFERENCE AS INT)) AS ReferralKey,
'ADAPT.PROP_WP_GEN' AS RecordSource,
R.ValidFrom, R.ValidTo, R.IsCurrent
FROM ADAPT.PROP_CAND_PRAP R;
GO
