CREATE VIEW [ADAPT].[LINK_Referral_RequestingSite]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(P.REFERENCE AS INT)) AS ReferralKey,
TRIM(ST_LOCATION) AS RequestingSiteKey,
'ADAPT.PROP_CAND_PRAP' AS RecordSource,
MIN(P.ValidFrom) AS ValidFrom, MAX(ValidTo) AS ValidTo, CAST(1 AS BIT) AS IsCurrent
FROM ADAPT.PROP_CAND_PRAP P
WHERE NULLIF(ST_LOCATION,'') IS NOT NULL 
GROUP BY TRIM(ST_LOCATION), P.REFERENCE;
GO
