CREATE VIEW [ADAPT].[LINK_Vacancy_EmploymentSite] AS SELECT
	CONCAT_WS('|','ADAPT',CAST(J.JOB_ID AS INT)) AS VacancyKey,
	CONCAT_WS('|','ADAPT', CAST(C.CLIENT_ID AS INT)) AS EmploymentSiteKey,
	'ADAPT.PROP_X_CLIENT_JOB' AS RecordSource,
	CJ.ValidFrom, 
	CJ.ValidTo, 
	CJ.IsCurrent
FROM
	ADAPT.PROP_X_CLIENT_JOB		AS CJ
	INNER JOIN
	ADAPT.PROP_JOB_GEN			AS J
	ON CJ.JOB = J.REFERENCE
	INNER JOIN
	ADAPT.PROP_CLIENT_GEN		AS C
	ON CJ.CLIENT = C.REFERENCE;
GO
