CREATE VIEW [ADAPT].[LINK_Case_OutcomeScore] AS SELECT
	CONCAT_WS('|','ADAPT',CAST(P.WIZPROG AS INT)) AS CaseKey
	, CONCAT_WS('|','ADAPT',CAST(S.REFERENCE AS INT), S.BISUNIQUEID) AS OutcomeScoreKey
	, 'ADAPT.PROP_X_CAND_WP' AS RecordSource
	, P.ValidFrom
	, P.ValidTo
	, P.IsCurrent
FROM ADAPT.PROP_X_CAND_WP P
INNER JOIN ADAPT.PROP_SOC_IMP_HIST S ON S.REFERENCE = P.CANDIDATE AND P.IsCurrent = '1';