CREATE VIEW [ADAPT].[LINK_Referral_RequestingOrganisation]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(P.REFERENCE AS INT)) AS ReferralKey,
TRIM(P.ORG_NAME) AS RequestingOrganisationKey,
'ADAPT.PROP_CAND_PRAP' AS RecordSource,
MIN(P.ValidFrom) AS ValidFrom, MAX(ValidTo) AS ValidTo, CAST(1 AS BIT) AS IsCurrent
FROM ADAPT.PROP_CAND_PRAP P
WHERE NULLIF(ORG_NAME,'') IS NOT NULL 
GROUP BY TRIM(P.ORG_NAME) , P.REFERENCE;
GO
