CREATE VIEW [ADAPT].[LINK_Vacancy_Assignment] AS SELECT 
	CONCAT_WS('|','ADAPT',CAST(J.JOB_ID AS INT)) AS VacancyKey,
	CONCAT_WS('|','ADAPT', CAST(A.ASSIG_ID AS INT)) AS AssignmentKey,
	'ADAPT.PROP_X_ASSIG_CAND' AS RecordSource,
	A.ValidFrom, 
	A.ValidTo, 
	A.IsCurrent
FROM
	ADAPT.PROP_X_ASSIG_CAND		AS XA
	LEFT JOIN
	ADAPT.PROP_JOB_GEN			AS J
	ON J.REFERENCE = XA.JOB
	LEFT JOIN
	ADAPT.PROP_ASSIG_GEN		AS A
	ON XA.ASSIGNMENT = A.REFERENCE
	WHERE J.JOB_ID IS NOT NULL
	AND A.ASSIG_ID IS NOT NULL;
GO