CREATE VIEW [ADAPT].[LINK_Barriers_Activity]
AS (
SELECT
CONCAT_WS('|','ADAPT',CAST(bg.[REFERENCE] AS INT)) AS BarrierKey,
CONCAT_WS('|','ADAPT',CAST(ag.[REFERENCE] AS INT)) AS ActivityKey,
'ADAPT.PROP_BARRIER_GEN'						AS RecordSource,
bg.[ValidFrom], 
bg.[ValidTo], 
bg.IsCurrent 
FROM ADAPT.PROP_BARRIER_GEN bg
INNER JOIN ADAPT.PROP_ACTIVITY_GEN ag ON ag.BARRIER = bg.BARRIER
);
GO

