CREATE VIEW [ADAPT].[LINK_Referral_Programme]
AS 
SELECT 
CONCAT_WS('|','ADAPT',CAST(P.REFERENCE AS INT)) AS ReferralKey,
TRIM(P.NAME) AS ProgrammeKey,
'ADAPT.PROP_WP_GEN' AS RecordSource,
P.ValidFrom, P.ValidTo, P.IsCurrent
FROM ADAPT.PROP_WP_GEN P
WHERE NULLIF(P.NAME,'') IS NOT NULL AND NULLIF(CAST(P.REFERENCE AS INT),'') IS NOT NULL;
