CREATE VIEW [ADAPT].[LINK_RequestingSite_RequestingOrganisation]
AS SELECT 
TRIM(ST_LOCATION)  AS RequestingSiteKey,
TRIM(ORG_NAME) AS RequestingOrganisationKey,
'ADAPT.PROP_CAND_PRAP' AS RecordSource,
MIN(ValidFrom) AS ValidFrom, MAX(ValidTo) AS ValidTo, CAST(1 AS BIT) AS IsCurrent
FROM ADAPT.PROP_CAND_PRAP
WHERE NULLIF(TRIM(ST_LOCATION),'') IS NOT NULL AND NULLIF(TRIM(ORG_NAME),'') IS NOT NULL 
GROUP BY TRIM(ST_LOCATION), TRIM(ORG_NAME);
GO