CREATE VIEW [ADAPT].[LINK_Case_Document] AS SELECT
CONCAT_WS('|','ADAPT',CAST(LK.REFERENCE AS INT)) AS CaseKey,
CONCAT_WS('|','ADAPT',CAST(D.ID AS INT)) AS DocumentKey,
'ADAPT.PROP_DOCTRACK_GEN' AS RecordSource,
D.ValidFrom, D.ValidTo, D.IsCurrent
FROM ADAPT.PROP_DOCTRACK_GEN D 
INNER JOIN ADAPT.PROP_X_PC_DOC LK ON LK.DOCTRACK = D.REFERENCE;
GO