CREATE VIEW [ADAPT].[LINK_Case_ASSIGNMENT] AS SELECT 
CONCAT_WS('|','ADAPT', CAST(C.CONTRACT AS INT)) AS CaseKey,
CONCAT_WS('|','ADAPT', CAST(P.ASSIG_ID AS INT)) AS ASSIGNMENTKey,
'ADAPT.PROP_X_CAND_WP' AS RecordSource,
P.ValidFrom, 
P.ValidTo, 
P.IsCurrent
FROM ADAPT.PROP_ASSIG_GEN P
INNER JOIN ADAPT.PROP_X_ASSIG_CAND C
ON C.ASSIGNMENT = P.REFERENCE WHERE C.CONTRACT IS NOT NULL;
GO
