CREATE VIEW [ADAPT].[LINK_Referral_ReferralDocument]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(CP.REFERENCE AS INT)) AS ReferralKey,
CONCAT_WS('|','ADAPT',CAST(DT.REFERENCE AS INT)) AS ReferralDocumentKey,
'ADAPT.PROP_X_PC_DOC' AS RecordSource,
X.ValidFrom, X.ValidTo, X.IsCurrent
FROM ADAPT.PROP_X_PC_DOC X
INNER JOIN ADAPT.PROP_DOCTRACK_GEN DT ON DT.REFERENCE = X.DOCTRACK 
INNER JOIN ADAPT.PROP_CAND_PRAP CP ON CP.REFERENCE = X.REFERENCE;
GO