CREATE VIEW [ADAPT].[PROP_X_ASSIG_CAND]
AS SELECT [BISUNIQUEID], [ASSIGNMENT], [CANDIDATE], [JOB], [CONTRACT], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_ASSIG_CAND UNION ALL SELECT [BISUNIQUEID], [ASSIGNMENT], [CANDIDATE], [JOB], [CONTRACT], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_ASSIG_CAND_History;
