CREATE VIEW [ADAPT].[PROP_X_WP_GRADING]
AS SELECT [BISUNIQUEID], [REFERENCE], [GRADING], [EMPLOYEE], [DATE_CHANGE], [TIME_CHANGE], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_WP_GRADING;
