CREATE VIEW [ADAPT].[PROP_BENEF_STATUS]
AS SELECT [BISUNIQUEID], [REFERENCE], [BENEF_STATUS], [LENGTH], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_BENEF_STATUS UNION ALL SELECT [BISUNIQUEID], [REFERENCE], [BENEF_STATUS], [LENGTH], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_BENEF_STATUS_History;
