CREATE VIEW [ADAPT].[PROP_ASSIG_FEE]
AS SELECT [BISUNIQUEID], [REFERENCE], [SALARY], [FEE], [FEE_TYPE], 0 AS [CRED_AMOUNT], 0 AS [REAS_CREDIT], [FEE_PERC], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_ASSIG_FEE;
