CREATE VIEW [ADAPT].[PROP_SI_HOBBIES]
AS SELECT [BISUNIQUEID], [REFERENCE], [HOBBIES], [FREQUENCY], [STATUS], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_SI_HOBBIES;
