CREATE VIEW [ADAPT].[PROP_X_CAND_WP]
AS SELECT [BISUNIQUEID], [WIZPROG], [CANDIDATE], [PROG_TMPL], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_CAND_WP UNION ALL SELECT [BISUNIQUEID], [WIZPROG], [CANDIDATE], [PROG_TMPL], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_CAND_WP_History;
