CREATE VIEW [ADAPT].[PROP_CAND_ID]
AS SELECT [BISUNIQUEID], [ID_TYPE], [REFERENCE], [ID_REF], [ID_VERIF_DT], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_CAND_ID UNION ALL SELECT [BISUNIQUEID], [ID_TYPE], [REFERENCE], [ID_REF], [ID_VERIF_DT], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_CAND_ID_History;
