CREATE VIEW [ADAPT].[PROP_X_CLIENT_JOB]
AS SELECT [BISUNIQUEID], [CLIENT], [CONTACT], [JOB], [CONFID], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_CLIENT_JOB UNION ALL SELECT [BISUNIQUEID], [CLIENT], [CONTACT], [JOB], [CONFID], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_CLIENT_JOB_History;
