CREATE VIEW [ADAPT].[PROP_X_CUST_ANSR]
AS SELECT [BISUNIQUEID], [OCC_ID], [ADD_NOTES], [MANDATORY], [QUESTION], [ASSESSMENT], [ANSWER], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_CUST_ANSR;
