CREATE VIEW [ADAPT].[PROP_IND_SECT]
AS SELECT [BISUNIQUEID], [REFERENCE], [INDUSTRY], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_IND_SECT UNION ALL SELECT [BISUNIQUEID], [REFERENCE], [INDUSTRY], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_IND_SECT_History;
