CREATE VIEW [ADAPT].[PROP_SI_SUPPORT]
AS SELECT [BISUNIQUEID], [REFERENCE], [PROFESSION], [FREQUENCY], [STATUS], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_SI_SUPPORT UNION ALL SELECT [BISUNIQUEID], [REFERENCE], [PROFESSION], [FREQUENCY], [STATUS], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_SI_SUPPORT_History;
