CREATE VIEW [ADAPT].[PROP_X_ORG_SITE]
AS SELECT [BISUNIQUEID], [ORG], [SITE], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_ORG_SITE UNION ALL SELECT [BISUNIQUEID], [ORG], [SITE], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_ORG_SITE_History;
