CREATE VIEW [ADAPT].[PROP_DSUB_GEN]
AS SELECT [BISUNIQUEID], [REFERENCE], [TITLE], [COMPANY], [CONTACT], 0 AS [PHONE], [INT_DATE1], [INT_DATE2], [INT_DATE3], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_DSUB_GEN;
