CREATE VIEW [ADAPT].[PROP_IV_GEN]
AS SELECT [BISUNIQUEID], [REFERENCE], [IV_CONT], [STAGE], [IV_DATE], [IV_START], [IV_END], [IV_ID], [FEEDBACK], [IV_ATT], [FEEDBACK_CAN], [FEEDBACK_CLT], [F_IV_CHB], [SE_IV_CHB], [TH_IV_CHB], [FOUR_IV_CHB], [FIFTH_IV_CHB], [NO_SHOW], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_IV_GEN;
