CREATE VIEW [ADAPT].[PROP_JOB_CAT]
AS SELECT [BISUNIQUEID], [REFERENCE], [JOB_CATEGORY], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_JOB_CAT UNION ALL SELECT [BISUNIQUEID], [REFERENCE], [JOB_CATEGORY], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_JOB_CAT_History; 
