CREATE VIEW [ADAPT].[PROP_X_VAC_SITE]
AS SELECT [BISUNIQUEID], [VACANCY], [SITE], [SITE_ROLE], [CONTACT], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_VAC_SITE;
