CREATE VIEW [ADAPT].[PROP_SOC_IMP_HIST]
AS 
SELECT [BISUNIQUEID], [REFERENCE], [Q1_ANSWER], [Q2_ANSWER], [Q3_ANSWER], [Q4_ANSWER], [Q5_ANSWER], [Q6_ANSWER], [Q7_ANSWER], [TOTAL], [COLOR], [ANSWER_DATE], [Q8_ANSWER], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_SOC_IMP_HIST;
;
