CREATE VIEW [ADAPT].[PROP_X_DUPL_CAND]
AS SELECT [BISUNIQUEID], [IMPORT], [DUPLICATE], [CANDIDATE], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_DUPL_CAND UNION ALL SELECT [BISUNIQUEID], [IMPORT], [DUPLICATE], [CANDIDATE], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_PROP_X_DUPL_CAND_History;
