CREATE VIEW [ADAPT].[SAT_Participant_Adapt_Address]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(PG.PERSON_ID AS INT)) AS ParticipantKey,
A.STREET1 AS AddressLine1,
A.STREET2 AS AddressLine2,
A.LOCALITY AS Locality,
A.TOWN AS Town,
A.COUNTY AS County,
A.POST_CODE AS PostCode,
CAST(A.POSTCODEAREA AS INT) AS PostCodeSector,
A.ValidFrom,
A.ValidTo,
A.IsCurrent
FROM ADAPT.PROP_ADDRESS A 
INNER JOIN ADAPT.PROP_PERSON_GEN PG ON A.REFERENCE = PG.REFERENCE and PG.IsCurrent = 1
	WHERE A.OCC_ID = 2034421;
