CREATE VIEW [ADAPT].[SAT_Case_Adapt_Dates]
AS SELECT 
CONCAT_WS('|','ADAPT',CAST(C.REFERENCE AS INT)) AS CaseKey,
 CAST(START_DATE AS DATE) AS StartDate
,CAST(START_VER_DT AS DATE)  AS StartVerifiedDate
,CAST(LEAVE_DATE AS DATE)  AS LeaveDate
,CAST(LEAVE_VER_DT AS DATE)  AS LeaveVerifiedDate
,CAST(PR_LEAVE_DT AS DATE)  AS ProjectedLeaveDate
,CAST(REPORT_DT AS DATE)  AS ReportDate
,CAST(SLA_DT AS DATE)  AS ReferralSLADate,
C.ValidFrom, C.ValidTo, C.IsCurrent
FROM ADAPT.PROP_WP_GEN C;