CREATE VIEW [ADAPT].[SAT_Entity_SoftDelete_Adapt_Core] AS SELECT
CONCAT_WS('|','ADAPT',CAST(ET.ENTITY_ID AS INT)) AS EntityKey
,'ADAPT.ENTITY_TABLE' AS RecordSource
,STATUS
,CREATED_BY
,UPDATED_BY
,DELETED_BY
,ValidFrom
,ValidTo
,IsCurrent
FROM ADAPT.ENTITY_TABLE ET
WHERE ISNULL(ET.STATUS,'D') = 'D';
GO
