CREATE VIEW [ADAPT].[SAT_Participant_Adapt_Equality]
AS SELECT
CONCAT_WS('|','ADAPT',CAST(PG.PERSON_ID AS INT)) AS ParticipantKey,
CAST(CG.SEX_ORIENT AS BIGINT) AS SexualOrientation,
CAST(CG.GENDER AS BIGINT) AS Gender,
CAST(E.ETHNIC_ORIG AS BIGINT) AS Ethnicity,
PG.ValidFrom,
PG.ValidTo,
PG.IsCurrent
FROM ADAPT.PROP_CAND_GEN CG 
INNER JOIN ADAPT.PROP_PERSON_GEN PG ON CG.REFERENCE = PG.REFERENCE and CG.IsCurrent = 1
LEFT JOIN ADAPT.PROP_EQUAL_GEN E ON E.REFERENCE = PG.REFERENCE AND E.IsCurrent = 1;