CREATE VIEW [ADAPT].[SAT_Assignment_Adapt_Core] AS (
SELECT
	CONCAT_WS('|','ADAPT',CAST(A.ASSIG_ID AS INT))	AS AssignmentKey,
	CONCAT_WS('|','ADAPT',CAST(A.REFERENCE AS INT))	AS AssignmentReference,
	A.JOB_TITLE										AS AssignmentTitle, 
	A.CONTR_TYPE									AS AssignmentStartContractType, 
	A.LEAVE_DT										AS AssignmentLeaveDate,
	ET.CREATEDDATE									AS AssignmentAddDate,
	A.ASSIG_TYPE									AS AssignmentType, 
	A.LEAVE_REASON									AS AssignmentLeaveReason, 
	A.INDUSTRY										AS AssignmentIndustry, 
	A.STATUS										AS AssignmentStatus, 
	A.V_JOBST_DT									AS AssignmentStartDate, 
	A.WRA_TYPE										AS WorkRelatedActivityType, 
	A.CONTR_WK_HRS									AS ContractedHours, 
	A.WK13_VER_DAT									AS AssignmentStartVerificationDate, 
	A.WK26_VER_DAT									AS AssignmentOutcomeTwoVerificationDate, 
	A.FAIL_SUS_DAT									AS AssignmentOutcomeTwoFailedDate, 
	A.CLAIM_DATE									AS AssignmentStartClaimDate, 
	A.CLAIM_YEAR									AS AssignmentStartClaimYear, 
	A.END_DT										AS WorkTrialEndDate, 
	A.SUS_OC_DT										AS AssignmentOutcomeTwoClaimedDate, 
	A.SUS_OC_C_Y									AS AssignmentOutcomeTwoClaimYear, 
	A.WK13_OC_F_DT									AS AssignmentOutcomeOneFailedDate, 
	A.WK13_OC_V_DT									AS AssignmentOutcomeOneVerifiedDate, 
	A.WK13_OC_C_DT									AS AssignmentOutcomeOneClaimedDate, 
	A.WK13_OC_C_Y									AS AssignmentOutcomeOneClaimYear, 
	A.UNSUPPORT_DT									AS UnsupportedDate, 
	A.UNSUP_DT_VER									AS UnsupportedDateVerified, 
	A.SELF_EMPL_YN									AS SelfEmployed, 
	A.SH_OUT_FAIL									AS FailedAssignmentStartDate, 
	A.DISC_MILE										AS DiscountMilestone, 
	A.SUS_OC_DT_52									AS AssignmentOutcomeThreeClaimedDate, 
	A.FAIL_SUS_52									AS AssignmentOutcomeThreeFailedDate, 
	A.CLAIM_YR_52									AS AssignmentOutcomeThreeClaimYear, 
	A.WK52_VER_DAT									AS AssignmentOutcomeThreeVerifiedDate, 
	A.EMP_CONSENT									AS EmployerConsentGiven, 
	A.PAY_CYCLE										AS AssignmentStartPaymentCycle, 
	A.FIRST_PAY										AS AssignmentStartFirstPaymentDate, 
	A.OWNER_JS										AS AssignmentOwningEmployee, 
	A.SEV											AS AssignmentSelfEmployedVerified, 
	A.WAGE_CAT										AS WageCategory,
	A.WEEKLY_HRS									AS WeeklyHours, 
	A.HOURLY_RATE									AS HourlyRate, 
	A.WAGE_EX										AS WageException, 
	A.TEMPPERM										AS TempPerm, 
	A.EST_END_DT									AS EstimatedAssignmentEndDate,
	A.ValidFrom										AS ValidFrom,
	A.ValidTo										AS ValidTo,
	A.IsCurrent										AS IsCurrent

FROM
	ADAPT.PROP_ASSIG_GEN AS A
	LEFT OUTER JOIN ADAPT.ENTITY_TABLE ET ON ET.ENTITY_ID = A.REFERENCE AND ET.IsCurrent = 1
	);
GO
