CREATE VIEW [ADAPT].[VW_LK_ENTITY_ROLE]
AS SELECT [REFERENCE], [ROLE_ID], [DEFAULT_ROLE], [DEFAULT_VALUE], [ValidFrom], [ValidTo], [row_sha2], CAST(1 AS BIT) AS IsCurrent FROM DELTA.ADAPT_VW_LK_ENTITY_ROLE UNION ALL SELECT [REFERENCE], [ROLE_ID], [DEFAULT_ROLE], [DEFAULT_VALUE], [ValidFrom], [ValidTo], [row_sha2], CAST(0 AS BIT) AS IsCurrent FROM DELTA.ADAPT_VW_LK_ENTITY_ROLE_History;
GO